import type { UnifiedPortfolioContext } from "@/lib/portfolio-context/contracts";
import type { PortfolioDecisionBackendResult } from "@/lib/portfolio-decision/backend";
import { assembleCurrentEvidence, createFourDecisionScenarios, createSimulationEvaluation } from "./workflow-actions";
import type { Comparison } from "@/lib/portfolio-decision/v32";

const evidenceExample = `[{"securityId":"00000000-0000-4000-8000-000000000001","selectionRequestId":"00000000-0000-4000-8000-000000000002","sleeve":"LONG_TERM_CORE","modelReferenceId":"00000000-0000-4000-8000-000000000003"}]`;
const candidateExample = `[{"securityId":"00000000-0000-4000-8000-000000000001","permission":"LOCKED","humanApprovedCandidate":false,"targetMarketValue":"0"}]`;

export function DecisionWorkflow({ portfolioId, context, scenarios, comparison, workflowStatus, contextId, evidenceManifestId }: { portfolioId: string; context: UnifiedPortfolioContext | null; scenarios: PortfolioDecisionBackendResult | null; comparison:Comparison|null; workflowStatus?: string; contextId?: string; evidenceManifestId?: string }) {
  if (!portfolioId) return null;
  const holdId = comparison?.scenarios.find((item) => item.scenarioType === "HOLD_CURRENT")?.scenarioId;
  const accepted = scenarios?.ok ? scenarios.data.find((item) => item.humanDecision?.conclusion === "ACCEPTED") : undefined;
  return <section className="space-y-5 rounded-2xl border border-cyan-300/15 bg-slate-900/35 p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300/70">Executable decision workflow</p><h2 className="mt-2 text-xl font-semibold text-white">Assemble, compare, decide, and evaluate</h2><p className="mt-2 text-sm leading-6 text-slate-400">Each operation reaches the owner-isolated Spring public API. IDs refer to sealed database records; prices, evidence hashes, and model labels are never entered by the browser.</p></div>{workflowStatus && <p role="status" className="rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-3 font-mono text-xs text-cyan-100">{workflowStatus}</p>}
    <div className="grid gap-4 xl:grid-cols-3">
      <form action={assembleCurrentEvidence} className="space-y-3 rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">1. Current evidence</h3><input type="hidden" name="portfolioId" value={portfolioId}/><Field name="accountSnapshotIds" label="Sealed snapshot IDs" placeholder="UUID, UUID"/><Field name="constraintPolicyVersionId" label="Constraint policy version ID"/><Area name="evidenceReferences" label="ID-only evidence references" placeholder={evidenceExample}/><button className="action">Assemble current context</button></form>
      <form action={createFourDecisionScenarios} className="space-y-3 rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">2. Four deterministic scenarios</h3><p className="text-xs text-slate-500">Creation seals all four projections without choosing a recommendation. Inspect the economic results below before selecting.</p><input type="hidden" name="portfolioId" value={portfolioId}/><Field name="contextId" label="Context ID" value={contextId || context?.contextId}/><Field name="evidenceManifestId" label="Evidence manifest ID" value={evidenceManifestId}/><Field name="constraintPolicyVersionId" label="Constraint policy version ID"/><div className="grid grid-cols-3 gap-2"><Field name="newMoneyAmount" label="New money" value="0"/><Field name="coreBudget" label="Core max" value="1"/><Field name="quantBudget" label="Quant max" value="0"/></div><Area name="candidates" label="Human candidate permissions" placeholder={candidateExample}/><button className="action">Create and inspect all four scenarios</button></form>
      <form action={createSimulationEvaluation} className="space-y-3 rounded-xl border border-slate-800 p-4"><h3 className="font-semibold text-white">4. Simulation evaluation</h3><p className="text-xs text-slate-500">Step 3 is the human conclusion recorded only after the exact-four comparison. Spring derives the first eligible completed entry session; HOLD_CURRENT remains a distinct comparator.</p><input type="hidden" name="portfolioId" value={portfolioId}/><Field name="scenarioId" label="Accepted scenario ID" value={accepted?.scenarioId}/><Field name="humanDecisionId" label="Accepted human decision ID" value={accepted?.humanDecision?.decisionId}/><Field name="startingContextId" label="Starting context ID" value={context?.contextId}/><Field name="holdCurrentScenarioId" label="HOLD_CURRENT comparator ID" value={holdId}/><button className="action">Create simulation evaluation</button></form>
    </div><p className="text-xs leading-5 text-slate-500">Scenario targets remain deterministic candidates for human review. The workflow cannot place orders, determine final weights autonomously, or upgrade NOT_VALIDATED evidence.</p></section>;
}

function Field({ name, label, placeholder, value }: { name: string; label: string; placeholder?: string; value?: string }) { return <label className="block text-xs text-slate-300">{label}<input required name={name} defaultValue={value} placeholder={placeholder} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-xs text-white"/></label>; }
function Area({ name, label, placeholder }: { name: string; label: string; placeholder: string }) { return <label className="block text-xs text-slate-300">{label}<textarea required name={name} placeholder={placeholder} className="mt-1 min-h-28 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 font-mono text-[0.65rem] text-white"/></label>; }
