import { randomUUID } from "node:crypto";
import type { PortfolioDecisionBackendResult } from "@/lib/portfolio-decision/backend";
import { humanConclusions } from "@/lib/portfolio-decision/contracts";
import { recordHumanDecision } from "./decision-actions";

function money(value: string | null) { if (value === null) return "Not available"; const amount = Number(value); return Number.isFinite(amount) ? new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(amount) : value; }
function percent(value: string) { const amount = Number(value); return Number.isFinite(amount) ? `${(amount * 100).toFixed(2)}%` : value; }

export function DecisionScenarios({ result, portfolioId }: { result: PortfolioDecisionBackendResult | null; portfolioId: string }) {
  if (!result) return null;
  if (!result.ok) return <section className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5"><h2 className="font-semibold text-amber-100">Decision scenarios unavailable</h2><p className="mt-2 text-sm text-slate-400">{result.error.message}</p><p className="mt-2 font-mono text-xs text-slate-600">{result.error.code}</p></section>;
  return <section className="space-y-5"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-300/70">Portfolio Decision Support v1</p><h2 className="mt-2 text-2xl font-semibold text-white">Human-controlled scenario comparison</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">The four deterministic scenarios remain separate from Fundamental Value and Quant scores. Costs, turnover, missing evidence, and NOT_VALIDATED labels stay visible. These are candidates for review, never orders or final weights.</p></header>
    {result.data.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-700 p-6 text-sm text-slate-500">No sealed V29 decision scenario exists for this portfolio.</div> : <div className="grid gap-5 xl:grid-cols-2">{result.data.map((scenario) => <article key={scenario.scenarioId} className={`rounded-2xl border p-5 ${scenario.candidateState === "NO_FEASIBLE_CANDIDATE" ? "border-rose-300/20 bg-rose-300/5" : "border-emerald-300/15 bg-slate-900/45"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.12em] text-slate-500">{scenario.scenarioType}</p><h3 className="mt-2 text-lg font-semibold text-white">{scenario.candidateState === "CANDIDATE_FOR_HUMAN_REVIEW" ? "Candidate for human review" : "No feasible candidate"}</h3></div><span className="rounded-full bg-amber-300/10 px-3 py-1 text-xs font-semibold text-amber-100">{scenario.scenarioState}</span></div>
        <p className="mt-3 text-xs text-slate-500">Cutoff {scenario.decisionCutoff}</p>
        {scenario.economics ? <div className="mt-5 grid grid-cols-2 gap-3 text-xs"><Metric label="Gross traded" value={money(scenario.economics.grossTradedNotional)}/><Metric label="Cost + slippage" value={money(scenario.economics.estimatedTransactionAndSlippageCost)}/><Metric label="One-way turnover" value={percent(scenario.economics.oneWayWeightTurnover)}/><Metric label="Final cash" value={money(scenario.economics.finalCash)}/><Metric label="Impact" value={scenario.economics.impactState}/><Metric label="Tax estimate" value={scenario.economics.taxEstimateState}/></div> : <p className="mt-5 rounded-xl border border-rose-300/15 p-3 text-sm text-rose-100">No numeric economics are presented because the scenario is infeasible.</p>}
        {(scenario.reasonCodes.length > 0 || scenario.recommendation.reasonCodes.length > 0) && <ul className="mt-4 space-y-1 font-mono text-xs text-amber-100">{[...new Set([...scenario.reasonCodes, ...scenario.recommendation.reasonCodes])].map((reason) => <li key={reason}>{reason}</li>)}</ul>}
        <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead className="text-slate-500"><tr><th className="py-2">Ticker</th><th>State</th><th>Evidence</th><th>Current</th><th>Target</th><th>Delta</th></tr></thead><tbody>{scenario.positions.map((position) => { const evidence = scenario.evidence.find((item) => item.securityId === position.securityId); return <tr key={position.securityId} className="border-t border-slate-800"><td className="py-2 font-semibold text-white">{position.ticker}</td><td>{evidence?.dataState ?? "MISSING"}</td><td className="text-amber-100">{evidence?.fundamentalEvidenceLabel ?? evidence?.quantEvidenceLabel ?? "NOT_AVAILABLE"}</td><td>{money(position.currentValue)}</td><td>{money(position.targetValue)}</td><td>{money(position.valueDelta)}</td></tr>; })}</tbody></table></div>
        {scenario.humanDecision ? <div className="mt-5 rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-4"><p className="font-semibold text-cyan-100">{scenario.humanDecision.conclusion}</p><p className="mt-2 text-sm text-slate-300">{scenario.humanDecision.rationale}</p><p className="mt-2 text-xs text-slate-500">{scenario.humanDecision.decidedAt}</p></div> : <form action={recordHumanDecision} className="mt-5 space-y-3 rounded-xl border border-slate-800 bg-slate-950/40 p-4"><input type="hidden" name="portfolioId" value={portfolioId}/><input type="hidden" name="scenarioId" value={scenario.scenarioId}/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><label className="block text-xs font-semibold text-slate-300" htmlFor={`rationale-${scenario.scenarioId}`}>Human rationale</label><textarea required minLength={1} maxLength={4000} id={`rationale-${scenario.scenarioId}`} name="rationale" className="min-h-24 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white" placeholder="Record the evidence considered and why you accept, reject, defer, or take no action."/><div className="flex flex-wrap gap-2">{humanConclusions.map((conclusion) => <button key={conclusion} name="conclusion" value={conclusion} type="submit" className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-semibold text-slate-200 hover:border-emerald-300/40">{conclusion.replace("_", " ")}</button>)}</div></form>}
        <p className="mt-4 break-all font-mono text-[0.65rem] text-slate-600">{scenario.contentHash}</p>
      </article>)}</div>}
    <div className="rounded-2xl border border-slate-800 bg-slate-900/35 p-5 text-sm leading-6 text-slate-400"><p className="font-semibold text-white">Authority boundary</p><p className="mt-2">A human conclusion records review only. It does not create an order, connect to a broker, grant an LLM decision authority, or turn NOT_VALIDATED research into a validated model.</p></div>
  </section>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-800 p-3"><p className="text-[0.65rem] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 break-all font-mono text-slate-200">{value}</p></div>; }
