"use client";

import { useActionState, useState } from "react";
import type { OnboardingInventory } from "@/lib/portfolio-onboarding/backend";
import { createAccount, createLiability, createManualSnapshot, createPortfolio, createPortfolioConstraints, linkPortfolioAccounts, recordLiabilityBalance, type OnboardingActionState } from "./onboarding-actions";

type CsvDiagnostic = { row: number | null; field: string | null; code: string; message: string };
type CsvPreview = { parserVersion: string; fileSha256: string; byteCount: number; dataRowCount: number; cashBalanceCount: number; positionCount: number; valid: boolean; diagnostics: CsvDiagnostic[] };
const sha256 = /^[0-9a-f]{64}$/;
const control = "w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white";
const button = "rounded-xl bg-emerald-300 px-4 py-2 text-xs font-bold text-slate-950 disabled:cursor-not-allowed disabled:opacity-40";
const initialOnboardingActionState: OnboardingActionState = { ok: false, code: "IDLE", message: "" };

export function OnboardingWorkspace({ inventory }: { inventory: OnboardingInventory }) {
  const [accountState, accountAction] = useActionState(createAccount, initialOnboardingActionState);
  const [portfolioState, portfolioAction] = useActionState(createPortfolio, initialOnboardingActionState);
  const [linkState, linkAction] = useActionState(linkPortfolioAccounts, initialOnboardingActionState);
  const [manualState, manualAction] = useActionState(createManualSnapshot, initialOnboardingActionState);
  const [liabilityState, liabilityAction] = useActionState(createLiability, initialOnboardingActionState);
  const [balanceState, balanceAction] = useActionState(recordLiabilityBalance, initialOnboardingActionState); const [constraintState, constraintAction] = useActionState(createPortfolioConstraints, initialOnboardingActionState);
  const [file, setFile] = useState<File | null>(null); const [csvAccount, setCsvAccount] = useState("");
  const [preview, setPreview] = useState<CsvPreview | null>(null); const [csvState, setCsvState] = useState(initialOnboardingActionState); const [busy, setBusy] = useState(false);
  if (!inventory.ok) return null;

  async function previewCsv() {
    if (!file || !csvAccount) return setCsvState({ ok: false, code: "CSV_INPUT_REQUIRED", message: "Choose an account and CSV file." });
    setBusy(true); setPreview(null); const body = new FormData(); body.set("accountId", csvAccount); body.set("file", file);
    try { const response = await fetch("/api/portfolio-onboarding/csv/preview", { method: "POST", body }); const value = await response.json() as unknown; if (!response.ok) { const error = value && typeof value === "object" ? value as { code?: unknown; message?: unknown } : {}; setCsvState({ ok: false, code: typeof error.code === "string" ? error.code : "CSV_PREVIEW_FAILED", message: typeof error.message === "string" ? error.message : "CSV preview failed." }); } else { const decoded = decodePreview(value); setPreview(decoded); setCsvState({ ok: true, code: "PREVIEW_COMPLETE", message: "Preview completed in Spring; raw CSV bytes were not persisted." }); } } catch { setCsvState({ ok: false, code: "CSV_PREVIEW_CONTRACT_ERROR", message: "CSV preview is unavailable or invalid." }); } finally { setBusy(false); }
  }

  async function commitCsv() {
    if (!file || !preview?.valid || !csvAccount) return; setBusy(true); const body = new FormData(); body.set("accountId", csvAccount); body.set("file", file); body.set("fileSha256", preview.fileSha256); body.set("idempotencyKey", crypto.randomUUID()); body.set("asOfTime", new Date(Math.floor(Date.now() / 1000) * 1000).toISOString());
    try { const response = await fetch("/api/portfolio-onboarding/csv/commit", { method: "POST", body }); const value = await response.json() as { code?: string; message?: string }; setCsvState(response.ok ? { ok: true, code: "CSV_COMMITTED", message: "CSV snapshot sealed through Spring." } : { ok: false, code: value.code || "CSV_COMMIT_FAILED", message: value.message || "CSV commit failed." }); } catch { setCsvState({ ok: false, code: "CSV_COMMIT_UNAVAILABLE", message: "CSV commit is unavailable." }); } finally { setBusy(false); }
  }

  const accountOptions = inventory.accounts.map((item) => [item.id, item.name] as [string, string]); const portfolioOptions = inventory.portfolios.map((item) => [item.id, item.name] as [string, string]);
  return <section className="space-y-5 rounded-2xl border border-slate-800 bg-slate-900/35 p-5"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-300/70">Executable onboarding</p><h2 className="mt-2 text-xl font-semibold text-white">Build the authoritative portfolio input</h2><p className="mt-2 text-sm text-slate-400">All writes pass through owner-isolated Spring APIs. CSV bytes remain transient for preview and commit.</p></div><div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">
    <ActionForm title="Create account" action={accountAction} state={accountState}><input className={control} name="name" required maxLength={160} placeholder="Taxable brokerage"/><select className={control} name="accountType" defaultValue="SIMULATED"><option>SIMULATED</option><option>REAL</option><option>RETIREMENT</option></select><Submit label="Create account"/></ActionForm>
    <ActionForm title="Create portfolio" action={portfolioAction} state={portfolioState}><input className={control} name="name" required maxLength={160} placeholder="Long-term and quant portfolio"/><Submit label="Create portfolio"/></ActionForm>
    <ActionForm title="Link accounts" action={linkAction} state={linkState}><Select name="portfolioId" label="Portfolio" options={portfolioOptions}/><div className="space-y-2">{inventory.accounts.map((account) => <label key={account.id} className="flex gap-2 text-sm text-slate-300"><input type="checkbox" name="accountIds" value={account.id}/>{account.name}</label>)}</div><Submit label="Update membership"/></ActionForm>
    <ManualSnapshotForm action={manualAction} state={manualState} accountOptions={accountOptions}/>
    <ActionForm title="Create liability" action={liabilityAction} state={liabilityState}><Select name="accountId" label="Account" options={accountOptions}/><input className={control} name="name" required maxLength={160} placeholder="Margin loan"/><select className={control} name="liabilityType" defaultValue="MARGIN"><option>MARGIN</option><option>LOAN</option><option>OTHER</option></select><Submit label="Create liability"/></ActionForm>
    <ActionForm title="Record liability balance" action={balanceAction} state={balanceState}><Select name="liabilityId" label="Liability" options={inventory.liabilities.map((item) => [item.id, item.name])}/><input className={control} name="balance" required inputMode="decimal" placeholder="Current balance"/><input className={control} name="annualInterestRate" inputMode="decimal" placeholder="Annual rate, e.g. 0.08"/><Submit label="Record balance"/></ActionForm>
    <ActionForm title="Portfolio constraints" action={constraintAction} state={constraintState}><Select name="portfolioId" label="Portfolio" options={portfolioOptions}/><input className={control} name="maximumPositionCount" inputMode="numeric" placeholder="Maximum position count"/><input className={control} name="maximumPositionWeight" inputMode="decimal" placeholder="Maximum position weight, e.g. 0.10"/><input className={control} name="maximumSectorWeight" inputMode="decimal" placeholder="Maximum sector weight"/><input className={control} name="minimumCashWeight" inputMode="decimal" placeholder="Minimum cash weight"/><input className={control} name="maximumLeverageRatio" inputMode="decimal" placeholder="Maximum leverage ratio"/><input className={control} name="maximumSpeculativeWeight" inputMode="decimal" placeholder="Maximum speculative weight"/><Submit label="Create constraint version"/></ActionForm>
    <div className="space-y-3 rounded-xl border border-slate-800 bg-slate-950/35 p-4"><h3 className="font-semibold text-white">CSV snapshot</h3><label className="block text-xs text-slate-400">Account<select className={`${control} mt-1`} required value={csvAccount} onChange={(event) => { setCsvAccount(event.target.value); setPreview(null); }}><option value="">Select</option>{accountOptions.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></label><input className={control} type="file" accept=".csv,text/csv" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); setCsvState(initialOnboardingActionState); }}/><div className="flex gap-2"><button type="button" className={button} disabled={busy || !file || !csvAccount} onClick={previewCsv}>Preview</button><button type="button" className={button} disabled={busy || !preview?.valid} onClick={commitCsv}>Commit exact preview</button></div><Status state={csvState}/>{preview && <div className="space-y-2 text-xs text-slate-400"><p>{preview.dataRowCount} rows / {preview.positionCount} positions / {preview.cashBalanceCount} cash rows</p><p className="break-all font-mono text-slate-600">{preview.fileSha256}</p>{preview.diagnostics.length > 0 && <ul className="space-y-1">{preview.diagnostics.map((item, index) => <li key={`${item.code}-${index}`} className="rounded-lg border border-amber-300/15 p-2"><span className="font-mono text-amber-100">{item.code}</span> {item.row !== null ? `row ${item.row}` : ""} {item.field ?? ""}: {item.message}</li>)}</ul>}</div>}</div>
  </div></section>;
}

function ActionForm({ title, action, state, children }: { title: string; action: (payload: FormData) => void; state: OnboardingActionState; children: React.ReactNode }) { return <form action={action} className="space-y-3 rounded-xl border border-slate-800 bg-slate-950/35 p-4"><h3 className="font-semibold text-white">{title}</h3>{children}<Status state={state}/></form>; }
function Submit({ label }: { label: string }) { return <button type="submit" className={button}>{label}</button>; }
function Status({ state }: { state: OnboardingActionState }) { return state.code === "IDLE" ? null : <p role="status" className={`text-xs ${state.ok ? "text-emerald-200" : "text-rose-200"}`}><span className="font-mono">{state.code}</span>: {state.message}</p>; }
function Select({ name, label, options }: { name: string; label: string; options: [string, string][] }) { return <label className="block text-xs text-slate-400">{label}<select className={`${control} mt-1`} name={name} required defaultValue=""><option value="">Select</option>{options.map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></label>; }

function ManualSnapshotForm({ action, state, accountOptions }: { action: (payload: FormData) => void; state: OnboardingActionState; accountOptions: [string, string][] }) {
  const [rows, setRows] = useState([0]);
  return <ActionForm title="Manual complete snapshot" action={action} state={state}><Select name="accountId" label="Account" options={accountOptions}/><input className={control} name="settledAmount" required inputMode="decimal" placeholder="Settled cash"/><div className="space-y-3">{rows.map((row, index) => <div key={row} className="space-y-2 rounded-lg border border-slate-800 p-3"><p className="text-xs font-semibold text-slate-400">Position {index + 1}</p><input className={control} name="securityPublicId" required placeholder="Canonical security UUID"/><input className={control} name="quantity" required inputMode="decimal" placeholder="Quantity"/><input className={control} name="averageCost" required inputMode="decimal" placeholder="Average cost"/>{rows.length > 1 && <button className="text-xs text-rose-200" type="button" onClick={() => setRows((current) => current.filter((value) => value !== row))}>Remove position</button>}</div>)}</div><div className="flex gap-2"><button className="rounded-xl border border-slate-700 px-4 py-2 text-xs font-semibold text-slate-200" type="button" disabled={rows.length >= 500} onClick={() => setRows((current) => [...current, Math.max(...current) + 1])}>Add position</button><Submit label="Seal manual snapshot"/></div></ActionForm>;
}

function decodePreview(value: unknown): CsvPreview {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Invalid CSV preview."); const row = value as Record<string, unknown>;
  const exact = ["byteCount", "cashBalanceCount", "dataRowCount", "diagnostics", "fileSha256", "parserVersion", "positionCount", "valid"].sort().join("|"); if (Object.keys(row).sort().join("|") !== exact) throw new Error("Invalid CSV preview fields.");
  if (typeof row.parserVersion !== "string" || !sha256.test(String(row.fileSha256)) || !Number.isSafeInteger(row.byteCount) || !Number.isSafeInteger(row.dataRowCount) || !Number.isSafeInteger(row.cashBalanceCount) || !Number.isSafeInteger(row.positionCount) || typeof row.valid !== "boolean" || !Array.isArray(row.diagnostics)) throw new Error("Invalid CSV preview values.");
  const diagnostics = row.diagnostics.map((item) => { if (!item || typeof item !== "object" || Array.isArray(item)) throw new Error("Invalid CSV diagnostic."); const diagnostic = item as Record<string, unknown>; if (Object.keys(diagnostic).sort().join("|") !== ["code", "field", "message", "row"].sort().join("|") || !(diagnostic.row === null || Number.isSafeInteger(diagnostic.row)) || !(diagnostic.field === null || typeof diagnostic.field === "string") || typeof diagnostic.code !== "string" || typeof diagnostic.message !== "string") throw new Error("Invalid CSV diagnostic values."); return diagnostic as CsvDiagnostic; });
  return { parserVersion: row.parserVersion, fileSha256: String(row.fileSha256), byteCount: Number(row.byteCount), dataRowCount: Number(row.dataRowCount), cashBalanceCount: Number(row.cashBalanceCount), positionCount: Number(row.positionCount), valid: row.valid, diagnostics };
}
