import type { UnifiedPortfolioContext } from "@/lib/portfolio-context/contracts";
import { formatPercentDecimal } from "@/lib/fundamental-value/presentation";

function money(value: string) { const negative = value.startsWith("-"); const [whole, fraction = ""] = (negative ? value.slice(1) : value).split("."); const hundred = BigInt(100); let cents = BigInt(whole) * hundred + BigInt((fraction + "00").slice(0, 2)); if ((fraction + "000")[2] >= "5") cents += BigInt(1); const dollars = cents / hundred; const remainder = (cents % hundred).toString().padStart(2, "0"); return `${negative ? "-" : ""}$${dollars.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}.${remainder}`; }
function percent(value: string) { return formatPercentDecimal(value, 1); }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><p className="text-[0.65rem] uppercase tracking-[0.13em] text-slate-500">{label}</p><p className="mt-2 font-mono text-xl font-semibold text-white">{value}</p></div>; }

export function PortfolioWorkspace({ context }: { context: UnifiedPortfolioContext }) {
  const value = context.riskContext; return <div className="space-y-6">
    <section className="rounded-3xl border border-emerald-300/15 bg-gradient-to-br from-slate-900/90 to-slate-950 p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex gap-2"><span className="rounded-full bg-emerald-300/10 px-3 py-1 text-xs font-semibold text-emerald-200">{value.state}</span><span className={`rounded-full px-3 py-1 text-xs font-semibold ${value.risk.status === "PASSED" ? "bg-cyan-300/10 text-cyan-200" : "bg-amber-300/10 text-amber-200"}`}>{value.risk.status}</span></div><h2 className="mt-5 text-2xl font-semibold text-white">Net portfolio value {money(value.totals.netPortfolioValue)}</h2><p className="mt-3 text-sm text-slate-400">As of {value.asOfTime}. Missing or stale valuations remain explicit and are never replaced with zero.</p></div><div className="text-right text-xs text-slate-500"><p>Context ID</p><p className="mt-1 max-w-xs break-all font-mono text-slate-300">{context.contextId}</p></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Assets" value={money(value.totals.assetValue)}/><Metric label="Cash" value={`${money(value.totals.cashValue)} / ${percent(value.totals.cashWeight)}`}/><Metric label="Invested" value={money(value.totals.investedValue)}/><Metric label="Liabilities" value={money(value.totals.liabilityValue)}/><Metric label="Leverage" value={percent(value.totals.leverageRatio)}/></section>
    <section className="grid gap-4 lg:grid-cols-2">{value.sleeves.map((sleeve) => <article key={sleeve.sleeve} className={`rounded-2xl border p-6 ${sleeve.sleeve === "LONG_TERM_CORE" ? "border-cyan-300/15 bg-cyan-300/5" : "border-violet-300/15 bg-violet-300/5"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.14em] text-slate-400">{sleeve.sleeve}</p><p className="mt-3 text-2xl font-semibold text-white">{money(sleeve.marketValue)}</p><p className="mt-1 text-sm text-slate-400">{percent(sleeve.assetWeight)} of assets / {sleeve.positionCount} positions</p></div><span className="rounded-full bg-amber-300/10 px-3 py-1 text-xs font-semibold text-amber-100">{sleeve.modelEvidenceLabel}</span></div><dl className="mt-5 space-y-2 text-xs"><div><dt className="text-slate-500">Model</dt><dd className="mt-1 font-mono text-slate-300">{sleeve.modelVersion}</dd></div><div><dt className="text-slate-500">Research use</dt><dd className="mt-1 text-slate-300">{sleeve.researchUseAllowed ? "Allowed with human review" : "Excluded"}</dd></div></dl></article>)}</section>
    {value.risk.reasonCodes.length > 0 && <section className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5"><h3 className="font-semibold text-amber-100">Risk review required</h3><ul className="mt-3 space-y-2 text-sm text-slate-400">{value.risk.reasonCodes.map((reason) => <li key={reason} className="font-mono">{reason}</li>)}</ul></section>}
    <section className={`rounded-2xl border p-5 ${context.review ? "border-emerald-300/20 bg-emerald-300/5" : "border-slate-700 bg-slate-900/35"}`}><h3 className="font-semibold text-white">Human review</h3>{context.review ? <div className="mt-3 space-y-2 text-sm text-slate-300"><p><span className="font-semibold text-emerald-200">{context.review.conclusion}</span> at {context.review.reviewedAt}</p><p>{context.review.rationale}</p><p className="break-all font-mono text-xs text-slate-500">{context.review.contentHash}</p></div> : <p className="mt-2 text-sm text-slate-400">No immutable human conclusion has been recorded for this context.</p>}</section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Maximum position" value={percent(value.constraints.maximumPositionWeight)}/><Metric label="Maximum sector" value={percent(value.constraints.maximumSectorWeight)}/><Metric label="Minimum cash" value={percent(value.constraints.minimumCashWeight)}/><Metric label="Maximum leverage" value={percent(value.constraints.maximumLeverageRatio)}/></section>
    <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/40"><div className="border-b border-slate-800 px-5 py-4"><h3 className="text-sm font-semibold text-white">Holdings and valuation state</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><thead className="bg-slate-950/60 text-slate-500"><tr><th className="px-5 py-3">Ticker</th><th className="px-5 py-3">Sleeve</th><th className="px-5 py-3">Sector</th><th className="px-5 py-3">State</th><th className="px-5 py-3">Value</th><th className="px-5 py-3">Weight</th></tr></thead><tbody>{value.positions.map((position) => <tr key={position.securityId} className="border-t border-slate-800/70"><td className="px-5 py-3 font-semibold text-white">{position.ticker}</td><td className="px-5 py-3 text-slate-300">{position.sleeve}</td><td className="px-5 py-3 font-mono text-slate-400">{position.sectorCode}</td><td className="px-5 py-3 text-slate-300">{position.dataState}</td><td className="px-5 py-3 font-mono text-slate-300">{position.marketValue ? money(position.marketValue) : "Missing"}</td><td className="px-5 py-3 font-mono text-slate-300">{position.assetWeight ? percent(position.assetWeight) : "Missing"}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/35 p-5 text-sm leading-6 text-slate-400"><p className="font-semibold text-white">Human control boundary</p><p className="mt-2">This snapshot describes portfolio context and constraint violations. Neither research sleeve can set final weights or create orders. Quant v2 is excluded from portfolio research authority after its unsupportive controlled replay.</p></section>
  </div>;
}
