import type { V32Result } from "@/lib/portfolio-decision/v32";
import { recordThesisReview, sealLongitudinalHorizon, selectComparisonScenario } from "./workflow-actions";

const horizons = [20, 60, 252, 504, 756] as const;

export function V32Workspace({ result }: { result: V32Result | null }) {
  if (!result) return null;
  if (!result.ok) return <section className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-5"><h2 className="font-semibold text-amber-100">V32 decision projection unavailable</h2><p className="mt-2 text-sm text-slate-400">{result.error}</p></section>;
  return <section className="space-y-5"><header><p className="text-xs font-semibold uppercase tracking-[0.16em] text-fuchsia-300/70">Portfolio decision projection v1</p><h2 className="mt-2 text-xl font-semibold text-white">Exact-four cohort and thesis review</h2><p className="mt-2 text-sm text-slate-400">The four scenarios are sealed atomically as one comparison before a recommendation or human acceptance. Spring alone seals mature longitudinal evidence and records human thesis reviews; the browser never computes prices or returns.</p></header>
    {result.comparison ? <div className="rounded-2xl border border-fuchsia-300/15 bg-slate-900/45 p-5"><div className="flex flex-wrap justify-between gap-3"><p className="font-semibold text-white">Exact 4 / 4 scenario cohort</p><span className="text-xs font-semibold text-fuchsia-100">{result.comparison.recommendationBindingState.replaceAll("_", " ")}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{result.comparison.scenarios.map(item => <div key={item.scenarioId} className="rounded-xl border border-slate-800 p-3"><p className="text-xs font-semibold text-slate-200">{item.scenarioType}</p><p className="mt-1 text-xs text-slate-400">{item.scenario.scenarioState} / {item.scenario.candidateState.replaceAll("_"," ")}</p><dl className="mt-3 space-y-1 text-xs"><Metric label="Traded" value={money(item.scenario.economics?.grossTradedNotional??null)}/><Metric label="Cost" value={money(item.scenario.economics?.estimatedTransactionAndSlippageCost??null)}/><Metric label="Turnover" value={pct(item.scenario.economics?.oneWayWeightTurnover??null)}/><Metric label="Final cash" value={money(item.scenario.economics?.finalCash??null)}/></dl><p className="mt-2 break-all font-mono text-[0.62rem] text-slate-600">{item.scenarioId}</p></div>)}</div>{result.comparison.recommendationBindingState==="AWAITING_RECOMMENDATION"&&<form action={selectComparisonScenario} className="mt-5 flex flex-wrap items-end gap-3 rounded-xl border border-fuchsia-300/15 p-4"><input type="hidden" name="portfolioId" value={result.comparison.portfolioId}/><input type="hidden" name="comparisonId" value={result.comparison.comparisonId}/><label className="text-xs text-slate-300">Select only after inspection<select name="selectedScenarioType" className="mt-1 block rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white">{result.comparison.scenarios.map(item=><option key={item.scenarioType}>{item.scenarioType}</option>)}</select></label><button className="action">Bind recommendation candidate</button></form>}</div> : <p className="rounded-xl border border-dashed border-slate-700 p-4 text-sm text-slate-500">No sealed exact-four comparison exists. Recommendation and human acceptance are not authorized.</p>}
    {result.longitudinal.map(projection => <article key={projection.evaluationId} className="rounded-2xl border border-slate-800 bg-slate-900/40 p-5"><p className="font-semibold text-white">Longitudinal evidence</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1040px] text-left text-xs"><thead className="text-slate-500"><tr><th className="py-2">Horizon</th><th>State</th><th>Gross</th><th>Net</th><th>True daily-path MDD</th><th>Coverage</th><th>Turnover</th><th>Cost</th><th>Thesis review</th></tr></thead><tbody>{projection.periods.map(period => { const review = projection.thesisReviews.find(value => value.horizonSessions === period.horizonSessions); return <tr key={period.horizonSessions} className="border-t border-slate-800"><td className="py-2">{period.horizonSessions}</td><td>{period.state.replaceAll("_", " ")}</td><td>{pct(period.grossReturn)}</td><td>{pct(period.netReturn)}</td><td>{pct(period.trueMaximumDrawdown)}</td><td>{period.coverageRate === null ? "UNAVAILABLE" : `${period.observationCount}/${period.expectedObservationCount} (${pct(period.coverageRate)})`}</td><td>{pct(period.totalTurnover)}</td><td>{money(period.totalCost)}</td><td>{review ? <><span className="font-semibold text-fuchsia-100">{review.state.replaceAll("_", " ")}</span><p className="mt-1 text-slate-500">{review.rationale}</p></> : "NOT REVIEWED"}</td></tr>; })}</tbody></table></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2"><form action={sealLongitudinalHorizon} className="space-y-3 rounded-xl border border-slate-800 p-4"><p className="font-semibold text-white">Seal natural maturity</p><p className="text-xs text-slate-500">Spring verifies authoritative session continuity and derives every value.</p><Hidden projection={projection}/><Horizon/><button className="action">Run controlled maturity seal</button></form><div className="space-y-3">{projection.periods.filter(period=>period.state==="AVAILABLE").map(period=>{const latest=projection.thesisReviews.find(value=>value.horizonSessions===period.horizonSessions);return <form key={period.horizonSessions} action={recordThesisReview} className="space-y-3 rounded-xl border border-slate-800 p-4"><p className="font-semibold text-white">Human thesis review · {period.horizonSessions} sessions</p><Hidden projection={projection}/><input type="hidden" name="horizonSessions" value={period.horizonSessions}/><input type="hidden" name="supersedesReviewId" value={latest?.reviewId??""}/><label className="block text-xs text-slate-300">Review state<select name="state" className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option>CONFIRMED</option><option>WEAKENED</option><option>INVALIDATED</option><option>INSUFFICIENT_EVIDENCE</option></select></label><label className="block text-xs text-slate-300">Rationale<textarea required maxLength={4000} name="rationale" className="mt-1 min-h-24 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"/></label><button className="action">{latest?"Supersede thesis review":"Record root thesis review"}</button></form>;})}</div></div>
    </article>)}
  </section>;
}

function Hidden({projection}:{projection:{portfolioId:string;scenarioId:string|null;evaluationId:string}}){return <><input type="hidden" name="portfolioId" value={projection.portfolioId}/><input type="hidden" name="scenarioId" value={projection.scenarioId ?? ""}/><input type="hidden" name="evaluationId" value={projection.evaluationId}/></>;}
function Horizon(){return <label className="block text-xs text-slate-300">Horizon<select name="horizonSessions" className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white">{horizons.map(value=><option key={value} value={value}>{value} sessions</option>)}</select></label>;}
function pct(value:string|null){return value===null?"UNAVAILABLE":`${(Number(value)*100).toFixed(2)}%`;}
function money(value:string|null){return value===null?"UNAVAILABLE":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(value));}
function Metric({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-2"><dt className="text-slate-500">{label}</dt><dd className="font-mono text-slate-200">{value}</dd></div>;}
