import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { decodeUnifiedPortfolioContext } from "./contracts.ts";

const hash = "sha256:" + "1".repeat(64);
function fixture() { return { contextId: "00000000-0000-4000-8000-000000000004", portfolioId: "00000000-0000-4000-8000-000000000003", recordedAt: "2026-08-13T00:00:01Z", review: null as null | Record<string, unknown>, riskContext: { resultVersion: "unified-portfolio-risk-result-v1.0.0", calculationVersion: "UNIFIED-PORTFOLIO-RISK-CALCULATION-v1.0.0", asOfTime: "2026-08-13T00:00:00+00:00", baseCurrency: "USD", state: "VALID", totals: { cashValue: "20000", investedValue: "80000", assetValue: "100000", liabilityValue: "0", netPortfolioValue: "100000", cashWeight: "0.2", leverageRatio: "0" }, positions: [{ securityId: "00000000-0000-4000-8000-000000000101", ticker: "AAPL", sleeve: "LONG_TERM_CORE", sectorCode: "45", dataState: "VALID", marketValue: "80000", assetWeight: "0.8" }], sectors: [{ sectorCode: "45", marketValue: "80000", assetWeight: "0.8" }], sleeves: [{ sleeve: "LONG_TERM_CORE", marketValue: "80000", assetWeight: "0.8", positionCount: 1, modelVersion: "FUNDAMENTAL-VALUE-v1.0.0", modelEvidenceLabel: "NOT_VALIDATED", researchUseAllowed: true, evidenceReferenceId: "fv", evidenceReferenceHash: hash }, { sleeve: "QUANT_TRADING", marketValue: "0", assetWeight: "0", positionCount: 0, modelVersion: "QUANT-TRADING-v1.1.0", modelEvidenceLabel: "NOT_VALIDATED", researchUseAllowed: true, evidenceReferenceId: "quant", evidenceReferenceHash: hash }], constraints: { maximumPositionWeight: "0.4", maximumSectorWeight: "0.6", minimumCashWeight: "0.1", maximumLeverageRatio: "0" }, risk: { status: "VIOLATED", reasonCodes: ["MAXIMUM_POSITION_WEIGHT_EXCEEDED"], constraintVersion: "UNIFIED-PORTFOLIO-CONSTRAINTS-v1.0.0" }, authority: { finalWeightAuthority: false, orderAuthority: false, automaticBrokerageExecution: false, llmDecisionAuthority: false, humanDecisionRequired: true }, contentHash: hash } }; }

test("decodes the human-controlled dual-sleeve contract", () => { const value = decodeUnifiedPortfolioContext(fixture()); assert.equal(value.riskContext.totals.netPortfolioValue, "100000"); assert.equal(value.riskContext.sleeves.length, 2); });
test("rejects automatic execution authority", () => { const value = fixture(); value.riskContext.authority.automaticBrokerageExecution = true; assert.throws(() => decodeUnifiedPortfolioContext(value)); });
test("rejects Quant v2 research authority", () => { const value = fixture(); value.riskContext.sleeves[1].modelVersion = "QUANT-TRADING-v2.0.0"; assert.throws(() => decodeUnifiedPortfolioContext(value)); });
test("rejects value substitution for missing positions", () => { const value = fixture(); value.riskContext.positions[0].dataState = "MISSING"; assert.throws(() => decodeUnifiedPortfolioContext(value)); });
test("decodes the shared Python-generated context fixture", () => { const value = JSON.parse(readFileSync("../contracts/unified-portfolio-risk-v1/context.example.json", "utf8")); assert.equal(decodeUnifiedPortfolioContext(value.contextResponse).riskContext.constraints.maximumPositionWeight, "0.4"); });
test("preserves an immutable human review and rejects unsafe review shape", () => { const value = fixture(); value.review = { reviewId: "00000000-0000-4000-8000-000000000005", conclusion: "REVIEW_REQUIRED", rationale: "Concentration requires review.", contentHash: hash, reviewedAt: "2026-08-13T00:00:02Z" }; assert.equal(decodeUnifiedPortfolioContext(value).review?.conclusion, "REVIEW_REQUIRED"); value.review.extraAuthority = true; assert.throws(() => decodeUnifiedPortfolioContext(value)); });
