import assert from "node:assert/strict";
import test from "node:test";
import { decodePortfolioDecisionScenario, decodePortfolioDecisionScenarios, PortfolioDecisionContractError } from "./contracts.ts";

const hash = `sha256:${"1".repeat(64)}`;
function fixture() { return { scenarioId: "00000000-0000-4000-8000-000000000001", portfolioId: "00000000-0000-4000-8000-000000000002", contextId: "00000000-0000-4000-8000-000000000003", scenarioType: "HOLD_CURRENT", scenarioState: "VALID", decisionCutoff: "2026-08-13T12:00:00Z", economicPolicyVersion: "PORTFOLIO-SCENARIO-ECONOMICS-v1.0.0", candidateState: "CANDIDATE_FOR_HUMAN_REVIEW", evidence: [{ securityId: "00000000-0000-4000-8000-000000000101", dataState: "VALID", fundamentalEvidenceLabel: "NOT_VALIDATED", quantEvidenceLabel: null }], positions: [{ securityId: "00000000-0000-4000-8000-000000000101", ticker: "AAPL", sleeve: "LONG_TERM_CORE", currentValue: "10000", targetValue: "10000", valueDelta: "0", targetWeight: "0.1", permission: "LOCKED", estimatedCost: "0", estimatedTax: null }], economics: { newMoneyAmount: "0", transactionCostBps: "2", slippageBps: "3", grossBuyNotional: "0", grossSellNotional: "0", grossTradedNotional: "0", estimatedTransactionAndSlippageCost: "0", impactState: "NOT_ESTIMATED", taxEstimateState: "NOT_ESTIMATED", taxEstimateAmount: null, appliedTaxAmount: "0", oneWayWeightTurnover: "0", grossTradedNotionalRate: "0", finalCash: "90000", finalAssetValue: "100000" }, reasonCodes: [], recommendation: { recommendationId: "00000000-0000-4000-8000-000000000004", state: "RECOMMENDATION_AVAILABLE", reasonCodes: [], contentHash: hash }, humanDecision: null, authority: { candidateForHumanReviewOnly: true, finalWeightAuthority: false, orderAuthority: false, automaticBrokerageExecution: false, llmDecisionAuthority: false, humanDecisionRequired: true }, contentHash: hash }; }

test("decodes a human-controlled NOT_VALIDATED scenario", () => { const decoded = decodePortfolioDecisionScenario(fixture()); assert.equal(decoded.scenarioType, "HOLD_CURRENT"); assert.equal(decoded.positions[0].valueDelta, "0"); assert.equal(decoded.evidence[0].fundamentalEvidenceLabel, "NOT_VALIDATED"); assert.equal(decoded.authority.orderAuthority, false); });

test("accepts exact arbitrary precision delta parity", () => { const value = fixture(); value.positions[0].currentValue = "10000000000000000000000000000000000000000.00000000000000000001"; value.positions[0].targetValue = "10000000000000000000000000000000000000000.00000000000000000002"; value.positions[0].valueDelta = "0.00000000000000000001"; assert.equal(decodePortfolioDecisionScenario(value).positions[0].valueDelta, "0.00000000000000000001"); });

test("rejects candidate, economics, and recommendation parity drift", () => { const value = fixture(); value.candidateState = "NO_FEASIBLE_CANDIDATE"; assert.throws(() => decodePortfolioDecisionScenario(value), PortfolioDecisionContractError); });

test("rejects unsafe authority", () => { const value = fixture(); value.authority.orderAuthority = true; assert.throws(() => decodePortfolioDecisionScenario(value), /Unsafe scenario authority/); });

test("preserves governed evidence labels without upgrading or downgrading", () => { const value = fixture(); value.evidence[0].fundamentalEvidenceLabel = "BACKTEST_SUPPORTED"; assert.equal(decodePortfolioDecisionScenario(value).evidence[0].fundamentalEvidenceLabel, "BACKTEST_SUPPORTED"); value.evidence[0].fundamentalEvidenceLabel = "GUARANTEED"; assert.throws(() => decodePortfolioDecisionScenario(value), /fundamentalEvidenceLabel/); });

test("rejects hidden fields and noncanonical decimals", () => { const hidden = { ...fixture(), finalWeights: [] }; assert.throws(() => decodePortfolioDecisionScenario(hidden), /fields/); const exponent = fixture(); exponent.economics.transactionCostBps = "2e0"; assert.throws(() => decodePortfolioDecisionScenario(exponent), /canonical decimal/); });

test("rejects unordered evidence and duplicate latest scenario types", () => { const value = fixture(); value.evidence.push({ ...value.evidence[0], securityId: "00000000-0000-4000-8000-000000000100" }); assert.throws(() => decodePortfolioDecisionScenario(value), /ordered/); assert.throws(() => decodePortfolioDecisionScenarios([fixture(), fixture()]), /one latest scenario/); });

test("decodes an infeasible no-action scenario honestly", () => { const value = fixture(); value.scenarioState = "INFEASIBLE"; value.candidateState = "NO_FEASIBLE_CANDIDATE"; value.economics = null; value.positions = []; value.reasonCodes = ["INCOMPLETE_PRICE_EVIDENCE"]; value.recommendation.state = "NO_FEASIBLE_ACTION"; value.recommendation.reasonCodes = ["INCOMPLETE_PRICE_EVIDENCE"]; const decoded = decodePortfolioDecisionScenario(value); assert.equal(decoded.economics, null); assert.equal(decoded.candidateState, "NO_FEASIBLE_CANDIDATE"); });

test("decodes immutable human conclusions", () => { const value = fixture(); value.humanDecision = { decisionId: "00000000-0000-4000-8000-000000000005", conclusion: "DEFERRED", rationale: "Evidence remains incomplete.", decidedAt: "2026-08-13T12:01:00Z", contentHash: hash }; assert.equal(decodePortfolioDecisionScenario(value).humanDecision?.conclusion, "DEFERRED"); });
