import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { decodeComparison, decodeLongitudinal, PortfolioDecisionV32ContractError } from "./v32.ts";

const ids=[1,2,3,4,5,6].map(n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`);
const hash=(digit:string)=>`sha256:${digit.repeat(64)}`;
test("decodes all four economic projections before recommendation selection",()=>{const value={comparisonId:ids[0],portfolioId:ids[1],contextId:ids[2],expectedScenarioCount:4,scenarios:["CONSTRAINED_REBALANCE","HOLD_CURRENT","NEW_MONEY_ONLY","TARGET_PORTFOLIO"].map((scenarioType,index)=>{const contentHash=hash(String(index+1)),scenarioId=ids[index+2];return{scenarioType,scenarioId,scenarioContentHash:contentHash,scenario:{scenarioId,scenarioType,scenarioState:"VALID",candidateState:"CANDIDATE_FOR_HUMAN_REVIEW",positions:[],economics:{grossTradedNotional:"0",estimatedTransactionAndSlippageCost:"0",oneWayWeightTurnover:"0",finalCash:"100000",finalAssetValue:"100000"},reasonCodes:[],contentHash}}}),selectedScenarioId:null,recommendationBindingState:"AWAITING_RECOMMENDATION",contentHash:hash("a"),sealedAt:"2026-08-13T12:00:00Z"};const decoded=decodeComparison(value,ids[1]);assert.equal(decoded.scenarios.length,4);assert.equal(decoded.scenarios[0].scenario.economics?.finalAssetValue,"100000");assert.throws(()=>decodeComparison({...value,sealedAt:"2026-08-13T12:00:00.100Z"},ids[1]),PortfolioDecisionV32ContractError);assert.throws(()=>decodeComparison({...value,selectedScenarioId:"00000000-0000-4000-8000-000000000099",recommendationBindingState:"RECOMMENDATION_BOUND"},ids[1]),PortfolioDecisionV32ContractError);assert.equal(decodeComparison({...value,selectedScenarioId:ids[5],recommendationBindingState:"RECOMMENDATION_BOUND"},ids[1]).selectedScenarioId,ids[5]);});
test("keeps unavailable longitudinal values explicit and decodes thesis review",()=>{const unavailable=(horizonSessions:number)=>({horizonSessions,state:"AWAITING_NATURAL_MATURITY",periodStart:null,periodEnd:null,expectedObservationCount:0,observationCount:0,coverageRate:null,grossReturn:null,netReturn:null,holdCurrentReturn:null,benchmarkReturn:null,excessVsHoldCurrent:null,excessVsBenchmark:null,trueMaximumDrawdown:null,totalTurnover:null,totalCost:null,contentHash:null});const value={evaluationId:ids[0],portfolioId:ids[1],periods:[20,60,252,504,756].map(unavailable),thesisReviews:[]};assert.equal(decodeLongitudinal(value,ids[1]).periods[0].grossReturn,null);});
test("rejects invalid dates and inconsistent available arithmetic",()=>{const unavailable=(horizonSessions:number)=>({horizonSessions,state:"AWAITING_NATURAL_MATURITY",periodStart:null,periodEnd:null,expectedObservationCount:0,observationCount:0,coverageRate:null,grossReturn:null,netReturn:null,holdCurrentReturn:null,benchmarkReturn:null,excessVsHoldCurrent:null,excessVsBenchmark:null,trueMaximumDrawdown:null,totalTurnover:null,totalCost:null,contentHash:null});const available={...unavailable(20),state:"AVAILABLE",periodStart:"2026-02-01",periodEnd:"2026-02-28",expectedObservationCount:21,observationCount:21,coverageRate:"1",grossReturn:"0.1",netReturn:"0.09",holdCurrentReturn:"0.08",benchmarkReturn:"0.07",excessVsHoldCurrent:"0.01",excessVsBenchmark:"0.02",trueMaximumDrawdown:"-0.05",totalTurnover:"0",totalCost:"1",contentHash:hash("b")};const root=(first:unknown)=>({evaluationId:ids[0],portfolioId:ids[1],periods:[first,60,252,504,756].map((v,index)=>index===0?v:unavailable(v as number)),thesisReviews:[]});assert.equal(decodeLongitudinal(root(available),ids[1]).periods[0].coverageRate,"1");for(const mutation of [{periodEnd:"2026-02-30"},{expectedObservationCount:20},{coverageRate:"0.9"},{excessVsHoldCurrent:"0.02"},{trueMaximumDrawdown:"-1.01"},{totalTurnover:"-0.01"},{totalCost:"-1"},{netReturn:"-1.01"}])assert.throws(()=>decodeLongitudinal(root({...available,...mutation}),ids[1]),PortfolioDecisionV32ContractError);});
test("browser V32 projection reaches Spring only and exposes no execution path",()=>{const source=readFileSync(new URL("./v32.ts",import.meta.url),"utf8");assert.match(source,/\/api\/v1\/me\/portfolios/);assert.doesNotMatch(source,/internal\/v1|analysis-python|brokerage|orderQuantity/);});
