CREATE TABLE analytics.exchange (
    mic CHAR(4) PRIMARY KEY,
    acronym VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    country_code CHAR(2) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    currency CHAR(3) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_exchange_acronym UNIQUE (acronym)
);

CREATE TABLE analytics.classification_node (
    taxonomy_code VARCHAR(64) NOT NULL,
    taxonomy_version VARCHAR(64) NOT NULL,
    node_code VARCHAR(64) NOT NULL,
    parent_node_code VARCHAR(64),
    level VARCHAR(16) NOT NULL,
    name VARCHAR(255) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (taxonomy_code, taxonomy_version, node_code),
    FOREIGN KEY (taxonomy_code, taxonomy_version, parent_node_code)
        REFERENCES analytics.classification_node (
            taxonomy_code, taxonomy_version, node_code
        ),
    CONSTRAINT ck_classification_node_level
        CHECK (level IN ('SECTOR', 'INDUSTRY_GROUP', 'INDUSTRY', 'SUB_INDUSTRY')),
    CONSTRAINT ck_classification_node_range
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_classification_node_parent
        CHECK (
            (level = 'SECTOR' AND parent_node_code IS NULL)
            OR (level <> 'SECTOR' AND parent_node_code IS NOT NULL)
        )
);

CREATE INDEX ix_classification_node_parent
    ON analytics.classification_node (
        taxonomy_code, taxonomy_version, parent_node_code
    );

CREATE TABLE analytics.company_profile_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    legal_name VARCHAR(255) NOT NULL,
    description TEXT,
    website_uri VARCHAR(2048),
    headquarters_country CHAR(2),
    fiscal_year_end_month SMALLINT,
    employee_count BIGINT,
    primary_mic CHAR(4) REFERENCES analytics.exchange (mic),
    taxonomy_code VARCHAR(64),
    taxonomy_version VARCHAR(64),
    sector_code VARCHAR(64),
    industry_code VARCHAR(64),
    effective_from DATE NOT NULL,
    effective_to DATE,
    revision_number INTEGER NOT NULL DEFAULT 1,
    source_record_id UUID NOT NULL REFERENCES analytics.source_record (id),
    available_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    quality_status VARCHAR(32) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_company_profile_revision
        UNIQUE (security_id, effective_from, source_record_id, revision_number),
    FOREIGN KEY (taxonomy_code, taxonomy_version, sector_code)
        REFERENCES analytics.classification_node (
            taxonomy_code, taxonomy_version, node_code
        ),
    FOREIGN KEY (taxonomy_code, taxonomy_version, industry_code)
        REFERENCES analytics.classification_node (
            taxonomy_code, taxonomy_version, node_code
        ),
    CONSTRAINT ck_company_profile_range
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_company_profile_revision CHECK (revision_number > 0),
    CONSTRAINT ck_company_profile_employee_count
        CHECK (employee_count IS NULL OR employee_count >= 0),
    CONSTRAINT ck_company_profile_fiscal_month
        CHECK (fiscal_year_end_month IS NULL OR fiscal_year_end_month BETWEEN 1 AND 12),
    CONSTRAINT ck_company_profile_times CHECK (ingested_at >= available_at),
    CONSTRAINT ck_company_profile_quality
        CHECK (quality_status IN ('VALIDATED', 'PROVISIONAL', 'REJECTED', 'NOT_VERIFIED')),
    CONSTRAINT ck_company_profile_taxonomy
        CHECK (
            (taxonomy_code IS NULL AND taxonomy_version IS NULL
                AND sector_code IS NULL AND industry_code IS NULL)
            OR (taxonomy_code IS NOT NULL AND taxonomy_version IS NOT NULL)
        )
);

CREATE INDEX ix_company_profile_security_effective
    ON analytics.company_profile_observation (
        security_id, effective_from DESC, available_at DESC
    );
CREATE INDEX ix_company_profile_classification
    ON analytics.company_profile_observation (
        taxonomy_code, taxonomy_version, sector_code, industry_code, effective_from
    );

CREATE TABLE analytics.security_status_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    status VARCHAR(32) NOT NULL,
    effective_date DATE NOT NULL,
    reason_code VARCHAR(64),
    delisting_date DATE,
    successor_security_id BIGINT REFERENCES analytics.security (id),
    revision_number INTEGER NOT NULL DEFAULT 1,
    source_record_id UUID NOT NULL REFERENCES analytics.source_record (id),
    available_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_security_status_revision
        UNIQUE (security_id, effective_date, source_record_id, revision_number),
    CONSTRAINT ck_security_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELISTED', 'ACQUIRED', 'BANKRUPT')),
    CONSTRAINT ck_security_status_revision CHECK (revision_number > 0),
    CONSTRAINT ck_security_status_times CHECK (ingested_at >= available_at),
    CONSTRAINT ck_security_status_delisting
        CHECK (
            (status = 'DELISTED' AND delisting_date IS NOT NULL)
            OR (status <> 'DELISTED' AND delisting_date IS NULL)
        ),
    CONSTRAINT ck_security_status_successor
        CHECK (successor_security_id IS NULL OR successor_security_id <> security_id)
);

CREATE INDEX ix_security_status_current
    ON analytics.security_status_observation (
        security_id, effective_date DESC, available_at DESC
    );
CREATE INDEX ix_security_status_delisted
    ON analytics.security_status_observation (status, delisting_date)
    WHERE status IN ('DELISTED', 'ACQUIRED', 'BANKRUPT');

CREATE TABLE analytics.dataset_definition (
    dataset_code VARCHAR(128) PRIMARY KEY,
    owner_service VARCHAR(32) NOT NULL,
    description TEXT NOT NULL,
    retention_class VARCHAR(32) NOT NULL,
    contains_licensed_raw_payload BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_dataset_owner CHECK (owner_service = 'PYTHON_ANALYTICS'),
    CONSTRAINT ck_dataset_retention
        CHECK (retention_class IN ('PERMANENT', 'AUDIT_7_YEARS', 'OPERATIONAL_2_YEARS')),
    CONSTRAINT ck_dataset_no_raw_payload
        CHECK (contains_licensed_raw_payload = FALSE)
);

CREATE TABLE analytics.dataset_release (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dataset_code VARCHAR(128) NOT NULL
        REFERENCES analytics.dataset_definition (dataset_code),
    dataset_version VARCHAR(128) NOT NULL,
    provider_id BIGINT REFERENCES analytics.data_provider (id),
    schema_version VARCHAR(64) NOT NULL,
    normalization_version VARCHAR(64) NOT NULL,
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    availability_lag_policy JSONB NOT NULL,
    definition_hash VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dataset_release UNIQUE (dataset_code, dataset_version),
    CONSTRAINT uq_dataset_release_hash UNIQUE (dataset_code, definition_hash),
    CONSTRAINT ck_dataset_release_range
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_dataset_release_policy
        CHECK (jsonb_typeof(availability_lag_policy) = 'object')
);

CREATE INDEX ix_dataset_release_effective
    ON analytics.dataset_release (dataset_code, effective_from DESC);

CREATE TRIGGER tr_exchange_append_only
BEFORE UPDATE OR DELETE ON analytics.exchange
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_classification_node_append_only
BEFORE UPDATE OR DELETE ON analytics.classification_node
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_company_profile_append_only
BEFORE UPDATE OR DELETE ON analytics.company_profile_observation
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_security_status_append_only
BEFORE UPDATE OR DELETE ON analytics.security_status_observation
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_dataset_definition_append_only
BEFORE UPDATE OR DELETE ON analytics.dataset_definition
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_dataset_release_append_only
BEFORE UPDATE OR DELETE ON analytics.dataset_release
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();

COMMENT ON TABLE analytics.company_profile_observation IS
    'Append-only point-in-time company profiles and normalized classification history.';
COMMENT ON TABLE analytics.security_status_observation IS
    'Append-only lifecycle evidence; analytics.security.active remains a legacy projection.';
COMMENT ON TABLE analytics.dataset_release IS
    'Provider-neutral dataset and normalization metadata; raw licensed payloads are excluded.';
