CREATE TABLE analytics.metric_definition (
    metric_code VARCHAR(128) NOT NULL,
    metric_version VARCHAR(64) NOT NULL,
    value_type VARCHAR(16) NOT NULL,
    unit_policy VARCHAR(64) NOT NULL,
    description TEXT NOT NULL,
    definition_hash VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (metric_code, metric_version),
    CONSTRAINT uq_metric_definition_hash UNIQUE (definition_hash),
    CONSTRAINT ck_metric_definition_value_type
        CHECK (value_type IN ('NUMERIC', 'TEXT', 'BOOLEAN'))
);

CREATE TABLE analytics.metric_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    metric_code VARCHAR(128) NOT NULL,
    metric_version VARCHAR(64) NOT NULL,
    observation_date DATE NOT NULL,
    period_start DATE,
    period_end DATE,
    status VARCHAR(32) NOT NULL,
    numeric_value NUMERIC(30, 12),
    text_value TEXT,
    boolean_value BOOLEAN,
    unit VARCHAR(64),
    currency CHAR(3),
    reason_code VARCHAR(64),
    reason_detail TEXT,
    dataset_release_id UUID REFERENCES analytics.dataset_release (id),
    source_record_id UUID REFERENCES analytics.source_record (id),
    effective_at TIMESTAMPTZ NOT NULL,
    available_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    revision_number INTEGER NOT NULL DEFAULT 1,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (metric_code, metric_version)
        REFERENCES analytics.metric_definition (metric_code, metric_version),
    CONSTRAINT uq_metric_observation_revision
        UNIQUE NULLS NOT DISTINCT (
            security_id, metric_code, metric_version, observation_date,
            period_start, period_end, revision_number
        ),
    CONSTRAINT ck_metric_observation_status
        CHECK (status IN ('VALID', 'MISSING', 'INVALID', 'NOT_APPLICABLE')),
    CONSTRAINT ck_metric_observation_period
        CHECK (period_start IS NULL OR period_end IS NULL OR period_end >= period_start),
    CONSTRAINT ck_metric_observation_revision CHECK (revision_number > 0),
    CONSTRAINT ck_metric_observation_times
        CHECK (available_at >= effective_at AND ingested_at >= available_at),
    CONSTRAINT ck_metric_observation_value CHECK (
        (
            status = 'VALID'
            AND reason_code IS NULL
            AND num_nonnulls(numeric_value, text_value, boolean_value) = 1
            AND source_record_id IS NOT NULL
        )
        OR (
            status <> 'VALID'
            AND numeric_value IS NULL
            AND text_value IS NULL
            AND boolean_value IS NULL
            AND reason_code IS NOT NULL
        )
    )
);

CREATE INDEX ix_metric_observation_pit
    ON analytics.metric_observation (
        security_id, metric_code, observation_date DESC,
        available_at DESC, ingested_at DESC
    );
CREATE INDEX ix_metric_observation_cohort
    ON analytics.metric_observation (
        metric_code, metric_version, observation_date, status, security_id
    );
CREATE INDEX ix_metric_observation_source
    ON analytics.metric_observation (source_record_id)
    WHERE source_record_id IS NOT NULL;

CREATE TABLE analytics.screening_scope (
    run_id UUID PRIMARY KEY REFERENCES analytics.screening_run (id),
    scope_type VARCHAR(16) NOT NULL,
    taxonomy_code VARCHAR(64),
    taxonomy_version VARCHAR(64),
    classification_node_code VARCHAR(64),
    methodology_reference VARCHAR(255) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (
        taxonomy_code, taxonomy_version, classification_node_code
    ) REFERENCES analytics.classification_node (
        taxonomy_code, taxonomy_version, node_code
    ),
    CONSTRAINT ck_screening_scope_type
        CHECK (scope_type IN ('UNIVERSE', 'SECTOR', 'INDUSTRY')),
    CONSTRAINT ck_screening_scope_classification CHECK (
        (scope_type = 'UNIVERSE'
            AND taxonomy_code IS NULL
            AND taxonomy_version IS NULL
            AND classification_node_code IS NULL)
        OR (scope_type IN ('SECTOR', 'INDUSTRY')
            AND taxonomy_code IS NOT NULL
            AND taxonomy_version IS NOT NULL
            AND classification_node_code IS NOT NULL)
    )
);

CREATE TABLE analytics.screening_group_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id UUID NOT NULL REFERENCES analytics.screening_run (id),
    strategy_version VARCHAR(128) NOT NULL
        REFERENCES analytics.strategy_definition (strategy_version),
    taxonomy_code VARCHAR(64) NOT NULL,
    taxonomy_version VARCHAR(64) NOT NULL,
    classification_node_code VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    eligible_count INTEGER NOT NULL,
    scored_count INTEGER NOT NULL,
    median_score NUMERIC(9, 4),
    group_rank INTEGER,
    reason_code VARCHAR(64),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (
        taxonomy_code, taxonomy_version, classification_node_code
    ) REFERENCES analytics.classification_node (
        taxonomy_code, taxonomy_version, node_code
    ),
    CONSTRAINT uq_screening_group_result
        UNIQUE (
            run_id, strategy_version, taxonomy_code,
            taxonomy_version, classification_node_code
        ),
    CONSTRAINT ck_screening_group_status
        CHECK (status IN ('SCORED', 'INSUFFICIENT_DATA', 'NOT_APPLICABLE')),
    CONSTRAINT ck_screening_group_counts
        CHECK (eligible_count >= 0 AND scored_count BETWEEN 0 AND eligible_count),
    CONSTRAINT ck_screening_group_values CHECK (
        (
            status = 'SCORED'
            AND scored_count > 0
            AND median_score BETWEEN 0 AND 100
            AND group_rank > 0
            AND reason_code IS NULL
        )
        OR (
            status <> 'SCORED'
            AND median_score IS NULL
            AND group_rank IS NULL
            AND reason_code IS NOT NULL
        )
    )
);

CREATE UNIQUE INDEX uq_screening_group_rank
    ON analytics.screening_group_result (
        run_id, strategy_version, taxonomy_code, taxonomy_version, group_rank
    )
    WHERE group_rank IS NOT NULL;
CREATE INDEX ix_screening_group_node
    ON analytics.screening_group_result (
        taxonomy_code, taxonomy_version, classification_node_code, run_id
    );

CREATE TRIGGER tr_metric_definition_append_only
BEFORE UPDATE OR DELETE ON analytics.metric_definition
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_metric_observation_append_only
BEFORE UPDATE OR DELETE ON analytics.metric_observation
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_screening_scope_immutable
BEFORE INSERT OR UPDATE OR DELETE ON analytics.screening_scope
FOR EACH ROW EXECUTE FUNCTION analytics.reject_completed_run_change();
CREATE TRIGGER tr_screening_group_result_immutable
BEFORE INSERT OR UPDATE OR DELETE ON analytics.screening_group_result
FOR EACH ROW EXECUTE FUNCTION analytics.reject_completed_run_change();

COMMENT ON TABLE analytics.metric_observation IS
    'Reusable PIT fundamental or factor evidence with explicit missing, invalid, and not-applicable states.';
COMMENT ON TABLE analytics.screening_group_result IS
    'Immutable sector or industry aggregates and ranks for a versioned screening run.';
