CREATE TABLE analytics.security (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(32) NOT NULL,
    exchange VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    instrument_type VARCHAR(32) NOT NULL,
    currency CHAR(3) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_security_symbol_exchange UNIQUE (symbol, exchange)
);

CREATE TABLE analytics.daily_price (
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    trading_date DATE NOT NULL,
    open_price NUMERIC(20, 6) NOT NULL,
    high_price NUMERIC(20, 6) NOT NULL,
    low_price NUMERIC(20, 6) NOT NULL,
    close_price NUMERIC(20, 6) NOT NULL,
    volume BIGINT NOT NULL,
    provider VARCHAR(64) NOT NULL,
    adjustment_mode VARCHAR(32) NOT NULL,
    source_timezone VARCHAR(64) NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (security_id, trading_date, provider, adjustment_mode),
    CONSTRAINT ck_daily_price_nonnegative_prices CHECK (
        open_price >= 0
        AND high_price >= 0
        AND low_price >= 0
        AND close_price >= 0
    ),
    CONSTRAINT ck_daily_price_nonnegative_volume CHECK (volume >= 0),
    CONSTRAINT ck_daily_price_range CHECK (
        high_price >= low_price
        AND high_price >= open_price
        AND high_price >= close_price
        AND low_price <= open_price
        AND low_price <= close_price
    )
);

CREATE INDEX ix_daily_price_trading_date
    ON analytics.daily_price (trading_date DESC);

INSERT INTO analytics.security (
    symbol,
    exchange,
    name,
    instrument_type,
    currency
)
VALUES
    ('AAPL', 'NASDAQ', 'Apple Inc.', 'COMMON_STOCK', 'USD'),
    ('MSFT', 'NASDAQ', 'Microsoft Corporation', 'COMMON_STOCK', 'USD'),
    ('JPM', 'NYSE', 'JPMorgan Chase & Co.', 'COMMON_STOCK', 'USD'),
    ('XOM', 'NYSE', 'Exxon Mobil Corporation', 'COMMON_STOCK', 'USD'),
    ('JNJ', 'NYSE', 'Johnson & Johnson', 'COMMON_STOCK', 'USD'),
    ('SPY', 'NYSE ARCA', 'SPDR S&P 500 ETF Trust', 'ETF', 'USD')
ON CONFLICT (symbol, exchange) DO NOTHING;
