ALTER TABLE analytics.security
    ADD COLUMN public_id UUID DEFAULT gen_random_uuid();

UPDATE analytics.security
SET public_id = gen_random_uuid()
WHERE public_id IS NULL;

ALTER TABLE analytics.security
    ALTER COLUMN public_id SET NOT NULL;

ALTER TABLE analytics.security
    ADD CONSTRAINT uq_security_public_id UNIQUE (public_id);

CREATE FUNCTION analytics.reject_security_public_id_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.public_id <> OLD.public_id THEN
        RAISE EXCEPTION 'Security public IDs are immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_security_public_id_immutable
BEFORE UPDATE OF public_id ON analytics.security
FOR EACH ROW EXECUTE FUNCTION analytics.reject_security_public_id_change();

CREATE TABLE analytics.data_provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    provider_schema_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_data_provider_code UNIQUE (code)
);

CREATE TABLE analytics.ingestion_batch (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_id BIGINT NOT NULL REFERENCES analytics.data_provider (id),
    request_key VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    parser_version VARCHAR(64) NOT NULL,
    normalization_version VARCHAR(64) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    failure_code VARCHAR(64),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ingestion_batch_request UNIQUE (provider_id, request_key),
    CONSTRAINT ck_ingestion_batch_status
        CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_ingestion_batch_completion
        CHECK (
            (status IN ('PENDING', 'RUNNING') AND completed_at IS NULL)
            OR (status IN ('SUCCEEDED', 'FAILED') AND completed_at IS NOT NULL)
        )
);

CREATE INDEX ix_ingestion_batch_provider_started
    ON analytics.ingestion_batch (provider_id, started_at DESC);
CREATE INDEX ix_ingestion_batch_status_started
    ON analytics.ingestion_batch (status, started_at);

CREATE TABLE analytics.source_record (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ingestion_batch_id UUID NOT NULL REFERENCES analytics.ingestion_batch (id),
    provider_id BIGINT NOT NULL REFERENCES analytics.data_provider (id),
    provider_record_id VARCHAR(255),
    source_reference VARCHAR(1024) NOT NULL,
    source_uri VARCHAR(2048),
    original_at TIMESTAMPTZ,
    available_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    schema_version VARCHAR(64) NOT NULL,
    revision_status VARCHAR(32) NOT NULL,
    quality_status VARCHAR(32) NOT NULL,
    content_hash VARCHAR(128) NOT NULL,
    storage_reference VARCHAR(2048),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_source_record_identity
        UNIQUE (provider_id, source_reference, content_hash),
    CONSTRAINT ck_source_record_ingestion_time
        CHECK (ingested_at >= available_at),
    CONSTRAINT ck_source_record_revision_status
        CHECK (revision_status IN ('AS_REPORTED', 'AS_FILED', 'RESTATED', 'CORRECTED', 'LEGACY')),
    CONSTRAINT ck_source_record_quality_status
        CHECK (quality_status IN ('VALIDATED', 'PROVISIONAL', 'REJECTED', 'NOT_VERIFIED'))
);

CREATE INDEX ix_source_record_provider_available
    ON analytics.source_record (provider_id, available_at);
CREATE INDEX ix_source_record_content_hash
    ON analytics.source_record (content_hash);
CREATE INDEX ix_source_record_batch
    ON analytics.source_record (ingestion_batch_id);

CREATE TABLE analytics.security_identifier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    identifier_type VARCHAR(32) NOT NULL,
    identifier_value VARCHAR(255) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    source_record_id UUID REFERENCES analytics.source_record (id),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_security_identifier_version
        UNIQUE (identifier_type, identifier_value, valid_from),
    CONSTRAINT ck_security_identifier_range
        CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE INDEX ix_security_identifier_lookup
    ON analytics.security_identifier (identifier_type, identifier_value, valid_from DESC);
CREATE INDEX ix_security_identifier_security
    ON analytics.security_identifier (security_id, valid_from DESC);

CREATE TABLE analytics.security_listing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    symbol VARCHAR(32) NOT NULL,
    exchange VARCHAR(64) NOT NULL,
    mic CHAR(4) NOT NULL,
    currency CHAR(3) NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE,
    source_record_id UUID REFERENCES analytics.source_record (id),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_security_listing_version
        UNIQUE (security_id, symbol, mic, valid_from),
    CONSTRAINT ck_security_listing_range
        CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE INDEX ix_security_listing_symbol
    ON analytics.security_listing (symbol, valid_from DESC);
CREATE INDEX ix_security_listing_security
    ON analytics.security_listing (security_id, valid_from DESC);
CREATE UNIQUE INDEX uq_security_listing_current_symbol
    ON analytics.security_listing (symbol)
    WHERE valid_to IS NULL;

CREATE TABLE analytics.security_classification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    classification_version VARCHAR(64) NOT NULL,
    raw_sector VARCHAR(255),
    raw_industry VARCHAR(255),
    normalized_sector VARCHAR(128),
    normalized_industry VARCHAR(128),
    sic_code VARCHAR(16),
    company_type VARCHAR(64) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    is_manual_override BOOLEAN NOT NULL DEFAULT FALSE,
    override_reason TEXT,
    reviewed_by VARCHAR(255),
    source_record_id UUID REFERENCES analytics.source_record (id),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_security_classification_version
        UNIQUE (security_id, classification_version, effective_from),
    CONSTRAINT ck_security_classification_range
        CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT ck_security_classification_override
        CHECK (
            NOT is_manual_override
            OR (override_reason IS NOT NULL AND reviewed_by IS NOT NULL)
        ),
    CONSTRAINT ck_security_classification_company_type
        CHECK (company_type IN (
            'MATURE_OPERATING_COMPANY', 'FINANCIAL', 'REIT', 'RESOURCE',
            'BIOTECHNOLOGY', 'EMERGING_GROWTH', 'SPECIAL_SITUATION', 'BENCHMARK'
        ))
);

CREATE INDEX ix_security_classification_security
    ON analytics.security_classification (security_id, effective_from DESC);
CREATE INDEX ix_security_classification_cohort
    ON analytics.security_classification
        (company_type, normalized_sector, effective_from);

INSERT INTO analytics.security_listing (
    security_id, symbol, exchange, mic, currency, valid_from
)
SELECT
    id,
    symbol,
    exchange,
    CASE exchange
        WHEN 'NASDAQ' THEN 'XNAS'
        WHEN 'NYSE' THEN 'XNYS'
        WHEN 'NYSE ARCA' THEN 'ARCX'
    END,
    currency,
    DATE '1970-01-01'
FROM analytics.security;
