INSERT INTO analytics.data_provider (code, name, provider_schema_version)
VALUES ('legacy_phase_1', 'Legacy Phase 1 Market Data', 'V2')
ON CONFLICT (code) DO NOTHING;

INSERT INTO analytics.ingestion_batch (
    provider_id,
    request_key,
    status,
    parser_version,
    normalization_version,
    started_at,
    completed_at
)
SELECT
    id,
    'flyway-v5-daily-price-backfill',
    'SUCCEEDED',
    'legacy-v2',
    'legacy-v2',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM analytics.data_provider
WHERE code = 'legacy_phase_1'
ON CONFLICT (provider_id, request_key) DO NOTHING;

INSERT INTO analytics.source_record (
    ingestion_batch_id,
    provider_id,
    source_reference,
    available_at,
    ingested_at,
    schema_version,
    revision_status,
    quality_status,
    content_hash
)
SELECT
    batch.id,
    provider.id,
    'database:migration/V2__create_market_data_tables.sql',
    batch.started_at,
    batch.completed_at,
    'V2',
    'LEGACY',
    'NOT_VERIFIED',
    'sha256:9ec71a2d09f090d7dc48db55c4102105d9744a51f296fe7b3214282f580b3fb0'
FROM analytics.ingestion_batch batch
JOIN analytics.data_provider provider ON provider.id = batch.provider_id
WHERE provider.code = 'legacy_phase_1'
  AND batch.request_key = 'flyway-v5-daily-price-backfill'
ON CONFLICT (provider_id, source_reference, content_hash) DO NOTHING;

CREATE TABLE analytics.daily_price_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    trading_date DATE NOT NULL,
    open_price NUMERIC(20, 6) NOT NULL,
    high_price NUMERIC(20, 6) NOT NULL,
    low_price NUMERIC(20, 6) NOT NULL,
    close_price NUMERIC(20, 6) NOT NULL,
    adjusted_close NUMERIC(20, 6),
    volume BIGINT NOT NULL,
    provider_id BIGINT NOT NULL REFERENCES analytics.data_provider (id),
    adjustment_mode VARCHAR(32) NOT NULL,
    source_timezone VARCHAR(64) NOT NULL,
    revision_number INTEGER NOT NULL DEFAULT 1,
    source_record_id UUID NOT NULL REFERENCES analytics.source_record (id),
    available_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    normalization_version VARCHAR(64) NOT NULL,
    quality_status VARCHAR(32) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_daily_price_observation_revision
        UNIQUE (security_id, trading_date, provider_id, adjustment_mode, revision_number),
    CONSTRAINT ck_daily_price_observation_prices
        CHECK (
            open_price >= 0 AND high_price >= 0 AND low_price >= 0
            AND close_price >= 0
            AND (adjusted_close IS NULL OR adjusted_close >= 0)
        ),
    CONSTRAINT ck_daily_price_observation_volume CHECK (volume >= 0),
    CONSTRAINT ck_daily_price_observation_range
        CHECK (
            high_price >= low_price
            AND high_price >= open_price
            AND high_price >= close_price
            AND low_price <= open_price
            AND low_price <= close_price
        ),
    CONSTRAINT ck_daily_price_observation_revision CHECK (revision_number > 0),
    CONSTRAINT ck_daily_price_observation_times CHECK (ingested_at >= available_at),
    CONSTRAINT ck_daily_price_observation_quality
        CHECK (quality_status IN ('VALIDATED', 'PROVISIONAL', 'REJECTED', 'NOT_VERIFIED'))
);

CREATE INDEX ix_daily_price_observation_security_date
    ON analytics.daily_price_observation
        (security_id, trading_date DESC, available_at DESC);
CREATE INDEX ix_daily_price_observation_date_mode
    ON analytics.daily_price_observation (trading_date, adjustment_mode);
CREATE INDEX ix_daily_price_observation_source
    ON analytics.daily_price_observation (source_record_id);

CREATE TABLE analytics.corporate_action (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    provider_id BIGINT NOT NULL REFERENCES analytics.data_provider (id),
    provider_action_id VARCHAR(255) NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    effective_date DATE NOT NULL,
    ex_date DATE,
    record_date DATE,
    payment_date DATE,
    amount NUMERIC(24, 10),
    currency CHAR(3),
    split_from NUMERIC(24, 10),
    split_to NUMERIC(24, 10),
    new_symbol VARCHAR(32),
    final_return NUMERIC(24, 10),
    revision_number INTEGER NOT NULL DEFAULT 1,
    source_record_id UUID NOT NULL REFERENCES analytics.source_record (id),
    available_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_corporate_action_revision
        UNIQUE (provider_id, provider_action_id, revision_number),
    CONSTRAINT ck_corporate_action_type
        CHECK (action_type IN (
            'DIVIDEND', 'SPLIT', 'SYMBOL_CHANGE', 'LISTING',
            'DELISTING', 'SPIN_OFF'
        )),
    CONSTRAINT ck_corporate_action_revision CHECK (revision_number > 0),
    CONSTRAINT ck_corporate_action_times CHECK (ingested_at >= available_at),
    CONSTRAINT ck_corporate_action_fields CHECK (
        (action_type <> 'DIVIDEND' OR (amount IS NOT NULL AND currency IS NOT NULL))
        AND (action_type <> 'SPLIT' OR (
            split_from IS NOT NULL AND split_from > 0
            AND split_to IS NOT NULL AND split_to > 0
        ))
        AND (action_type <> 'SYMBOL_CHANGE' OR new_symbol IS NOT NULL)
    )
);

CREATE INDEX ix_corporate_action_security_effective
    ON analytics.corporate_action (security_id, effective_date, action_type);
CREATE INDEX ix_corporate_action_security_available
    ON analytics.corporate_action (security_id, available_at);
CREATE INDEX ix_corporate_action_provider_action
    ON analytics.corporate_action (provider_id, provider_action_id);

CREATE TABLE analytics.fundamental_fact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    metric_code VARCHAR(128) NOT NULL,
    numeric_value NUMERIC(24, 10) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    currency CHAR(3),
    period_start DATE,
    period_end DATE NOT NULL,
    fiscal_year INTEGER,
    fiscal_period VARCHAR(16) NOT NULL,
    form_type VARCHAR(32) NOT NULL,
    accession_number VARCHAR(32) NOT NULL,
    filed_at TIMESTAMPTZ NOT NULL,
    available_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    mapping_version VARCHAR(64) NOT NULL,
    normalization_version VARCHAR(64) NOT NULL,
    revision_status VARCHAR(32) NOT NULL,
    quality_status VARCHAR(32) NOT NULL,
    source_record_id UUID NOT NULL REFERENCES analytics.source_record (id),
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fundamental_fact_source
        UNIQUE (
            security_id, metric_code, period_start, period_end,
            fiscal_period, source_record_id
        ),
    CONSTRAINT ck_fundamental_fact_period
        CHECK (period_start IS NULL OR period_end >= period_start),
    CONSTRAINT ck_fundamental_fact_times
        CHECK (available_at >= filed_at AND ingested_at >= available_at),
    CONSTRAINT ck_fundamental_fact_revision
        CHECK (revision_status IN ('AS_REPORTED', 'AS_FILED', 'RESTATED', 'CORRECTED')),
    CONSTRAINT ck_fundamental_fact_quality
        CHECK (quality_status IN ('VALIDATED', 'PROVISIONAL', 'REJECTED', 'NOT_VERIFIED'))
);

CREATE INDEX ix_fundamental_fact_security_metric
    ON analytics.fundamental_fact
        (security_id, metric_code, period_end DESC, available_at DESC);
CREATE INDEX ix_fundamental_fact_metric_period
    ON analytics.fundamental_fact (metric_code, period_end, available_at);
CREATE INDEX ix_fundamental_fact_source
    ON analytics.fundamental_fact (source_record_id);

CREATE TABLE analytics.market_value_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL REFERENCES analytics.security (id),
    metric_code VARCHAR(64) NOT NULL,
    observation_date DATE NOT NULL,
    numeric_value NUMERIC(24, 10) NOT NULL,
    unit VARCHAR(32) NOT NULL,
    currency CHAR(3),
    provider_id BIGINT NOT NULL REFERENCES analytics.data_provider (id),
    revision_number INTEGER NOT NULL DEFAULT 1,
    source_record_id UUID NOT NULL REFERENCES analytics.source_record (id),
    available_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL,
    normalization_version VARCHAR(64) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_market_value_observation_revision
        UNIQUE (
            security_id, metric_code, observation_date,
            provider_id, revision_number
        ),
    CONSTRAINT ck_market_value_observation_metric
        CHECK (metric_code IN ('MARKET_CAP', 'SHARES_OUTSTANDING', 'DILUTED_SHARES')),
    CONSTRAINT ck_market_value_observation_nonnegative
        CHECK (numeric_value >= 0),
    CONSTRAINT ck_market_value_observation_revision CHECK (revision_number > 0),
    CONSTRAINT ck_market_value_observation_times CHECK (ingested_at >= available_at)
);

CREATE INDEX ix_market_value_observation_security_metric
    ON analytics.market_value_observation
        (security_id, metric_code, observation_date DESC, available_at DESC);

INSERT INTO analytics.daily_price_observation (
    security_id,
    trading_date,
    open_price,
    high_price,
    low_price,
    close_price,
    volume,
    provider_id,
    adjustment_mode,
    source_timezone,
    source_record_id,
    available_at,
    ingested_at,
    normalization_version,
    quality_status
)
SELECT
    price.security_id,
    price.trading_date,
    price.open_price,
    price.high_price,
    price.low_price,
    price.close_price,
    price.volume,
    provider.id,
    price.adjustment_mode,
    price.source_timezone,
    source.id,
    price.ingested_at,
    price.ingested_at,
    'legacy-v2',
    'NOT_VERIFIED'
FROM analytics.daily_price price
CROSS JOIN analytics.data_provider provider
CROSS JOIN analytics.source_record source
WHERE provider.code = 'legacy_phase_1'
  AND source.provider_id = provider.id
  AND source.source_reference = 'database:migration/V2__create_market_data_tables.sql';

CREATE FUNCTION analytics.reject_immutable_observation_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Versioned analytics observations are append-only';
END;
$$;

CREATE TRIGGER tr_source_record_append_only
BEFORE UPDATE OR DELETE ON analytics.source_record
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_security_identifier_append_only
BEFORE UPDATE OR DELETE ON analytics.security_identifier
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_security_listing_append_only
BEFORE UPDATE OR DELETE ON analytics.security_listing
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_security_classification_append_only
BEFORE UPDATE OR DELETE ON analytics.security_classification
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_daily_price_observation_append_only
BEFORE UPDATE OR DELETE ON analytics.daily_price_observation
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_corporate_action_append_only
BEFORE UPDATE OR DELETE ON analytics.corporate_action
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_fundamental_fact_append_only
BEFORE UPDATE OR DELETE ON analytics.fundamental_fact
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
CREATE TRIGGER tr_market_value_observation_append_only
BEFORE UPDATE OR DELETE ON analytics.market_value_observation
FOR EACH ROW EXECUTE FUNCTION analytics.reject_immutable_observation_change();
