import "server-only";

const uuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const key = /^[A-Za-z0-9._:@+-]{1,128}$/;
export type MutationResult = { ok: true; payload: unknown } | { ok: false; code: string; message: string; status?: number };

function config(): { origin: URL; identity: string } | null { const raw = process.env.BACKEND_BASE_URL; const identity = process.env.CLOSED_TEST_IDENTITY; if (!raw || !identity || !key.test(identity)) return null; try { const origin = new URL(raw); if (!['http:', 'https:'].includes(origin.protocol) || origin.username || origin.password) return null; return { origin, identity }; } catch { return null; } }

export async function springJson(path: string, method: "POST" | "PUT", body: unknown, idempotencyKey?: string): Promise<MutationResult> { const configured = config(); if (!configured || !path.startsWith("/api/v1/me/")) return { ok: false, code: "ONBOARDING_CONFIGURATION_ERROR", message: "Portfolio onboarding is not configured." }; const headers: Record<string, string> = { Accept: "application/json", "Content-Type": "application/json", "X-Test-Identity": configured.identity }; if (idempotencyKey) { if (!key.test(idempotencyKey)) return { ok: false, code: "INVALID_IDEMPOTENCY_KEY", message: "The request identity is invalid." }; headers["Idempotency-Key"] = idempotencyKey; } try { return decode(await fetch(new URL(path, configured.origin), { method, cache: "no-store", signal: AbortSignal.timeout(15_000), headers, body: JSON.stringify(body) })); } catch { return { ok: false, code: "ONBOARDING_BACKEND_UNAVAILABLE", message: "The Spring onboarding API is unavailable." }; } }

export async function springCsv(path: string, form: FormData, headers: Record<string, string> = {}): Promise<MutationResult> { const configured = config(); if (!configured || !path.startsWith("/api/v1/me/")) return { ok: false, code: "ONBOARDING_CONFIGURATION_ERROR", message: "Portfolio onboarding is not configured." }; try { return decode(await fetch(new URL(path, configured.origin), { method: "POST", cache: "no-store", signal: AbortSignal.timeout(20_000), headers: { Accept: "application/json", "X-Test-Identity": configured.identity, ...headers }, body: form })); } catch { return { ok: false, code: "ONBOARDING_BACKEND_UNAVAILABLE", message: "The Spring CSV API is unavailable." }; } }

export function canonicalId(value: string): boolean { return uuid.test(value); }
async function decode(response: Response): Promise<MutationResult> { let payload: unknown; try { payload = await response.json(); } catch { return { ok: false, code: "ONBOARDING_NON_JSON_RESPONSE", message: "Spring returned a non-JSON response.", status: response.status }; } if (response.ok) return { ok: true, payload }; const row = payload && typeof payload === "object" ? payload as Record<string, unknown> : {}; return { ok: false, code: typeof row.code === "string" ? row.code : "ONBOARDING_BACKEND_ERROR", message: typeof row.message === "string" ? row.message : `Spring returned HTTP ${response.status}.`, status: response.status }; }
