import { humanize, formatTimestamp } from "@/lib/format";
import type { CurrentAssessment, CurrentRange } from "@/lib/fundamental-value/current-contracts";
import { formatPercentDecimal } from "@/lib/fundamental-value/presentation";

function percent(value: string): string { return formatPercentDecimal(value, 1); }
function range(value: CurrentRange, mode: "money" | "percent", currency = "USD"): string {
  return mode === "money"
    ? `${currency} ${value.low} / ${value.central} / ${value.high}`
    : `${percent(value.low)} / ${percent(value.central)} / ${percent(value.high)}`;
}

function Metric({ label, value }: { label: string; value: string }) {
  return <div className="rounded-2xl border border-slate-800 bg-slate-900/45 p-4"><p className="text-xs text-slate-400">{label}</p><p className="mt-2 font-mono text-xl font-semibold text-white">{value}</p></div>;
}

export function CurrentFundamentalValueWorkspace({ assessment }: { assessment: CurrentAssessment }) {
  return <div className="space-y-6">
    <section className="rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-900/90 to-slate-950 p-6 sm:p-8">
      <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-sm text-cyan-100">{assessment.identity.ticker} · {assessment.identity.mic} · {assessment.priceSessionDate}</p><h2 className="mt-3 text-2xl font-semibold text-white">{humanize(assessment.investmentView.category)}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Current-revision deterministic research output. It is explicitly NOT_VALIDATED and is not a buy order, ranking, target allocation, or promise of future return.</p></div><div className="rounded-2xl border border-amber-300/20 bg-amber-300/5 px-4 py-3 text-right"><p className="text-[0.62rem] uppercase tracking-[0.14em] text-amber-200/70">Risk-cap ceiling</p><p className="mt-1 font-mono text-xl font-semibold text-amber-100">{percent(assessment.riskCap.ceiling)}</p><p className="mt-1 text-[0.68rem] text-slate-500">Never a final portfolio weight</p></div></div>
      <div className="mt-6 flex flex-wrap gap-2">{assessment.investmentView.reasonCodes.map((reason) => <span key={reason} className="rounded-full bg-slate-800 px-3 py-1 font-mono text-[0.68rem] text-slate-300">{reason}</span>)}</div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Company quality" value={assessment.companyQuality.score} /><Metric label="Financial resilience" value={assessment.financialResilience.score} /><Metric label="Earnings and cash-flow quality" value={assessment.earningsAndCashFlowQuality.score} /><Metric label="Capital allocation quality" value={assessment.capitalAllocationQuality.score} /><Metric label="Downside risk" value={assessment.downsideRisk.score} /></section>
    <section className="grid gap-4 lg:grid-cols-4"><Metric label="Reference price" value={`${assessment.identity.currency} ${assessment.referencePrice.value}`} /><Metric label="Fair value low / central / high" value={range(assessment.fairValue, "money", assessment.identity.currency)} /><Metric label="Margin of safety low / central / high" value={range(assessment.marginOfSafety, "percent")} /><Metric label="Expected return low / central / high" value={range(assessment.expectedReturn, "percent")} /></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><h3 className="text-sm font-semibold text-white">Valuation methods</h3><div className="mt-4 grid gap-3 lg:grid-cols-2">{assessment.valuations.map((method) => <div key={method.method} className="rounded-xl border border-slate-800 bg-slate-950/45 p-4"><p className="text-xs font-semibold text-slate-200">{humanize(method.method)}</p><p className="mt-3 font-mono text-xs text-slate-400">{range(method, "money", assessment.identity.currency)}</p>{method.terminalValueShare !== null && <p className="mt-2 text-[0.68rem] text-slate-600">Terminal value share {percent(method.terminalValueShare)}</p>}</div>)}</div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/35 p-5"><h3 className="text-sm font-semibold text-white">Immutable evidence boundary</h3><dl className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><div><dt className="text-xs text-slate-500">Assessment ID</dt><dd className="mt-1 break-all font-mono text-xs">{assessment.assessmentId}</dd></div><div><dt className="text-xs text-slate-500">Decision cutoff</dt><dd className="mt-1 font-mono text-xs">{formatTimestamp(assessment.decisionCutoff)}</dd></div><div><dt className="text-xs text-slate-500">Latest fundamental period</dt><dd className="mt-1 font-mono text-xs">{assessment.latestFundamentalPeriodEnd}</dd></div><div><dt className="text-xs text-slate-500">Evidence label</dt><dd className="mt-1 font-mono text-xs">{assessment.modelEvidenceLabel}</dd></div><div><dt className="text-xs text-slate-500">Claim ceiling</dt><dd className="mt-1 break-words font-mono text-xs">{assessment.claimCeiling}</dd></div><div><dt className="text-xs text-slate-500">Formula</dt><dd className="mt-1 break-words font-mono text-xs">{assessment.versions.formulaVersion}</dd></div><div><dt className="text-xs text-slate-500">Assessment hash</dt><dd className="mt-1 break-all font-mono text-xs">{assessment.assessmentContentHash}</dd></div><div><dt className="text-xs text-slate-500">Risk reasons</dt><dd className="mt-1 break-words font-mono text-xs">{assessment.riskCap.bindingReasons.join(" · ")}</dd></div></dl></section>
    <section className="rounded-2xl border border-cyan-300/15 bg-cyan-300/5 p-5 text-sm leading-6 text-slate-400"><p className="font-semibold text-cyan-100">Human-controlled research only</p><p className="mt-2">No AI narrative, raw provider payload, automatic ranking, final portfolio weight, or brokerage execution is exposed or authorized.</p></section>
  </div>;
}
