import { humanize, formatTimestamp } from "@/lib/format";
import type { Condition, FundamentalValueDecision, ValueRange } from "@/lib/fundamental-value/contracts";
import { presentFundamentalValueDecision, formatPercentDecimal, rangeText } from "@/lib/fundamental-value/presentation";
import { StatusPill } from "./status-pill";

function Detail({ label, value }: { label: string; value: string | null }) {
  return <div><dt className="text-[0.65rem] uppercase tracking-[0.14em] text-slate-500">{label}</dt><dd className="mt-1 break-words font-mono text-xs text-slate-200">{value ?? "Not available"}</dd></div>;
}

function ReasonText({ reasons }: { reasons: string[] }) {
  return reasons.length > 0 ? <p className="mt-2 font-mono text-[0.65rem] text-amber-200/70">{reasons.join(" · ")}</p> : null;
}

function RangeCard({ label, range, percent, currency }: { label: string; range: ValueRange; percent?: boolean; currency?: string }) {
  return <div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><p className="text-[0.65rem] uppercase tracking-[0.13em] text-slate-500">{label}</p><p className="mt-3 font-mono text-sm font-semibold text-cyan-100">{rangeText(range, { percent, currency })}</p><ReasonText reasons={range.reasonCodes} /></div>;
}

function EvidenceList({ title, items }: { title: string; items: Condition[] }) {
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><h3 className="text-sm font-semibold text-white">{title}</h3><ul className="mt-4 space-y-3">{items.map((item) => <li key={item.code} className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800/70 pb-3 last:border-0 last:pb-0"><div><p className="text-xs font-medium text-slate-200">{humanize(item.code)}</p><p className="mt-1 font-mono text-[0.68rem] text-slate-500">Observed {item.observedValue ?? item.state} · threshold {item.threshold}</p><ReasonText reasons={item.reasonCodes} /></div><span className={item.satisfied === true ? "text-xs font-semibold text-amber-200" : "text-xs text-slate-400"}>{item.satisfied === null ? item.state : item.satisfied ? "Triggered" : "Not triggered"}</span></li>)}</ul></section>;
}

export function FundamentalValueWorkspace({ decision }: { decision: FundamentalValueDecision }) {
  const view = presentFundamentalValueDecision(decision);
  const assessment = decision.deterministicAssessment;
  return <div className="space-y-6">
    <section className="rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-900/90 to-slate-950 p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-3xl"><div className="flex flex-wrap gap-2"><StatusPill state={decision.state} /><StatusPill state={decision.applicability} /><StatusPill state={decision.modelEvidenceLabel ?? "NO_MODEL_RESULT"} /></div><p className="mt-5 font-mono text-sm text-cyan-100">{decision.identity.ticker} · {decision.identity.mic} · completed session {decision.identity.completedSessionDate}</p><h2 className="mt-3 text-2xl font-semibold text-white">{view.title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{view.summary}</p></div><div className="rounded-2xl border border-amber-300/20 bg-amber-300/5 px-4 py-3 text-right"><p className="text-[0.62rem] uppercase tracking-[0.14em] text-amber-200/70">LONG_TERM_CORE risk-cap ceiling</p><p className="mt-1 font-mono text-xl font-semibold text-amber-100">{decision.riskCapCeiling === null ? "Unavailable" : formatPercentDecimal(decision.riskCapCeiling, 0)}</p><p className="mt-1 text-[0.68rem] text-slate-500">Never a final portfolio weight</p></div></div>{view.reasons.length > 0 && <div className="mt-6 rounded-xl border border-slate-800 bg-slate-950/55 p-4"><p className="text-xs font-semibold text-slate-300">Reason codes</p><ul className="mt-2 flex flex-wrap gap-2">{view.reasons.map((reason) => <li key={reason} className="rounded-full bg-slate-800 px-3 py-1 font-mono text-[0.68rem] text-slate-300">{reason}</li>)}</ul></div>}</section>
    {assessment && <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><RangeCard label="Fair value low / central / high" range={assessment.fairValue} currency={assessment.currency} /><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><p className="text-[0.65rem] uppercase tracking-[0.13em] text-slate-500">Reference price</p><p className="mt-3 font-mono text-sm font-semibold text-cyan-100">{assessment.referencePrice.value === null ? assessment.referencePrice.state : `${assessment.currency} ${assessment.referencePrice.value}`}</p>{assessment.referencePrice.reasonCode && <ReasonText reasons={[assessment.referencePrice.reasonCode]} />}</div><RangeCard label="Margin of safety low / central / high" range={assessment.marginOfSafety} percent /><RangeCard label={`Annualized expected return (${assessment.projectionYears}-year horizon) low / central / high`} range={assessment.expectedReturn} percent /></section>
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{[["Company quality", assessment.companyQuality], ["Financial resilience", assessment.financialResilience], ["Earnings and cash-flow quality", assessment.earningsAndCashFlowQuality], ["Capital allocation quality", assessment.capitalAllocationQuality], ["Downside risk", assessment.downsideRisk]].map(([label, raw]) => { const metric = raw as typeof assessment.companyQuality; return <div key={label as string} className="rounded-2xl border border-slate-800 bg-slate-900/45 p-4"><p className="text-xs text-slate-400">{label as string}</p><p className="mt-2 font-mono text-xl font-semibold text-white">{metric.score ?? metric.state}</p><ReasonText reasons={metric.reasonCodes} /></div>; })}</section>
      <section className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><h3 className="text-sm font-semibold text-white">Valuation methods</h3><div className="mt-4 grid gap-3 lg:grid-cols-2">{assessment.valuations.map((method) => <div key={method.method} className="rounded-xl border border-slate-800 bg-slate-950/45 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-semibold text-slate-200">{humanize(method.method)}</p><StatusPill state={method.state} /></div><p className="mt-3 font-mono text-xs text-slate-400">{rangeText(method, { currency: assessment.currency })}</p>{method.terminalValueShare && <p className="mt-2 text-[0.68rem] text-slate-600">Terminal value share {method.terminalValueShare}</p>}<ReasonText reasons={method.reasonCodes} /></div>)}</div><div className="mt-4 border-t border-slate-800 pt-4"><p className="text-xs font-semibold text-slate-300">Risk-cap binding reasons</p><ReasonText reasons={assessment.riskCap.bindingReasons} /></div></section>
      <div className="grid gap-4 xl:grid-cols-3"><EvidenceList title="Thesis evidence" items={assessment.thesisEvidence} /><EvidenceList title="Counter-thesis evidence" items={assessment.counterThesisEvidence} /><EvidenceList title="Invalidation conditions" items={assessment.invalidationConditions} /></div>
    </>}
    <section className="rounded-2xl border border-slate-800 bg-slate-900/35 p-5"><h3 className="text-sm font-semibold text-white">Evidence and version seal</h3><dl className="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><Detail label="Ticker / MIC" value={`${decision.identity.ticker} / ${decision.identity.mic}`} /><Detail label="Security ID" value={decision.identity.securityId} /><Detail label="Listing ID" value={decision.identity.listingId} /><Detail label="Identity currency" value={decision.identity.currency} /><Detail label="Completed session" value={decision.identity.completedSessionDate} /><Detail label="Projection horizon" value={assessment ? `${assessment.projectionYears} years` : null} /><Detail label="Decision cutoff" value={formatTimestamp(decision.decisionCutoff)} /><Detail label="Sealed ingestion cutoff" value={formatTimestamp(decision.sealedIngestionCutoff)} /><Detail label="Evidence label" value={decision.modelEvidenceLabel ?? "No deterministic assessment"} /><Detail label="Claim ceiling" value={decision.claimCeiling} /><Detail label="Assembly ID" value={decision.assemblyId} /><Detail label="Manifest hash" value={decision.manifestContentHash} /><Detail label="Input seal hash" value={decision.inputSealContentHash} /><Detail label="Model / strategy" value={assessment ? `${assessment.modelVersion} · ${assessment.strategyVersion}` : null} /><Detail label="Formula / assumptions" value={assessment ? `${assessment.formulaVersion} · ${assessment.assumptionPolicyVersion}` : null} /><Detail label="Aggregation policy" value={assessment?.aggregationVersion ?? null} /><Detail label="Risk policy" value={assessment?.riskPolicyVersion ?? null} /><Detail label="Assessment content hash" value={assessment?.contentHash ?? null} /></dl></section>
    <section className="rounded-2xl border border-cyan-300/15 bg-cyan-300/5 p-5 text-sm leading-6 text-slate-400"><p className="font-semibold text-cyan-100">Deterministic calculation only</p><p className="mt-2">No AI narrative is included in this workspace. AI content cannot alter eligibility, valuation, ranking, risk caps, portfolio weights, or brokerage actions. The model is NOT_VALIDATED and does not guarantee returns.</p></section>
  </div>;
}
