import type { QuantResearchDecision, QuantResearchSignal } from "@/lib/quant-trading/contracts";

function CountCard({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900/45 p-5"><p className="text-[0.65rem] uppercase tracking-[0.13em] text-slate-500">{label}</p><p className="mt-2 font-mono text-2xl font-semibold text-white">{value}</p></div>; }
function candidateDetail(signal: QuantResearchSignal) { const entry = signal.entryPlan; return entry ? `signal ${entry.signalClose} / stop ${entry.initialStop} / max entry ${entry.maximumEntryPrice}` : signal.rawSignal.reasonCodes.join(" / ") || signal.assemblyReasonCodes.join(" / ") || "No additional reason"; }

export function QuantResearchWorkspace({ decision }: { decision: QuantResearchDecision }) {
  const counts = new Map<string, number>(); for (const signal of decision.signals) counts.set(signal.researchClassification, (counts.get(signal.researchClassification) ?? 0) + 1);
  const ordered = [...decision.signals].sort((left, right) => (left.ranking.rank ?? Number.MAX_SAFE_INTEGER) - (right.ranking.rank ?? Number.MAX_SAFE_INTEGER) || left.securityId.localeCompare(right.securityId));
  return <div className="space-y-6">
    <section className="rounded-3xl border border-violet-300/15 bg-gradient-to-br from-slate-900/90 to-slate-950 p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex gap-2"><span className="rounded-full bg-violet-300/10 px-3 py-1 text-xs font-semibold text-violet-200">QUANT v1.1</span><span className="rounded-full bg-amber-300/10 px-3 py-1 text-xs font-semibold text-amber-200">{decision.modelEvidenceLabel}</span></div><h2 className="mt-5 text-2xl font-semibold text-white">Five-session research snapshot</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Ranks combine medium-term momentum under explicit trend, liquidity, volatility, entry-price, stop and maximum-holding rules. A candidate is not a purchase instruction.</p></div><div className="text-right"><p className="text-xs text-slate-500">Decision date</p><p className="mt-1 font-mono text-sm text-violet-100">{decision.decisionDate}</p><p className="mt-2 text-xs text-slate-600">Denominator {decision.expectedSecurityCount}</p></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><CountCard label="Entry candidates" value={counts.get("ENTRY_CANDIDATE") ?? 0} /><CountCard label="Hold review" value={counts.get("HOLD_REVIEW") ?? 0} /><CountCard label="Exit review" value={counts.get("EXIT_REVIEW") ?? 0} /><CountCard label="No signal" value={counts.get("NO_SIGNAL") ?? 0} /><CountCard label="Insufficient" value={counts.get("INSUFFICIENT_EVIDENCE") ?? 0} /><CountCard label="Not applicable" value={counts.get("NOT_APPLICABLE") ?? 0} /></section>
    <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/40"><div className="border-b border-slate-800 px-5 py-4"><h3 className="text-sm font-semibold text-white">Ranked security research</h3><p className="mt-1 text-xs text-slate-500">Durable security IDs are shown because ticker presentation is intentionally outside this projection.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-slate-950/60 text-slate-500"><tr><th className="px-5 py-3">Rank</th><th className="px-5 py-3">Security</th><th className="px-5 py-3">Classification</th><th className="px-5 py-3">Composite</th><th className="px-5 py-3">Signal / entry context</th></tr></thead><tbody>{ordered.map((signal) => <tr key={signal.securityId} className="border-t border-slate-800/70"><td className="px-5 py-3 font-mono text-violet-200">{signal.ranking.rank ?? "—"}</td><td className="px-5 py-3 font-mono text-slate-300">{signal.securityId}</td><td className="px-5 py-3 font-semibold text-slate-200">{signal.researchClassification}</td><td className="px-5 py-3 font-mono text-slate-400">{signal.ranking.compositeScore ?? "—"}</td><td className="px-5 py-3 font-mono text-slate-500">{candidateDetail(signal)}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/35 p-5"><h3 className="text-sm font-semibold text-white">Immutable contract seal</h3><dl className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4 text-xs"><div><dt className="text-slate-500">Decision ID</dt><dd className="mt-1 break-all font-mono text-slate-300">{decision.decisionId}</dd></div><div><dt className="text-slate-500">Content hash</dt><dd className="mt-1 break-all font-mono text-slate-300">{decision.contentHash}</dd></div><div><dt className="text-slate-500">Assembly manifest</dt><dd className="mt-1 break-all font-mono text-slate-300">{decision.assemblyManifestHash}</dd></div><div><dt className="text-slate-500">Strategy / formula</dt><dd className="mt-1 font-mono text-slate-300">{decision.strategyVersion} / {decision.formulaVersion}</dd></div></dl></section>
    <section className="rounded-2xl border border-amber-300/15 bg-amber-300/5 p-5 text-sm leading-6 text-slate-400"><p className="font-semibold text-amber-100">Research support only</p><p className="mt-2">The model remains NOT_VALIDATED. Backtests do not guarantee future returns. No AI or deterministic component can set final portfolio weights, submit brokerage orders, or bypass human review.</p></section>
	</div>;
}
